.github/workflows/publish_npm_packages.yml

The NPM publish of the SDKs was not writing the correct version into the package.json

fix: npm publish not versioning correctly

---

cmd/database/database.go

I found that the database wasn't always available in time when running `keel test`.  Increased the wait from 2.5 seconds to 5 seconds.  It would be great to capture telemetry on this.
Also, previously, if the database wasn't ready, the error was misleading:
```
Error: ERROR: database "keel_e4bc5aa7b1d1de4a38651ee3c16d52b5" already exists (SQLSTATE 42P04)
```
Now returning this:
```
Error: failed to connect to `host=0.0.0.0 user=postgres database=`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
```

fix: increase cli database wait time and improved error message

---

cmd/database/database.go
integration/testdata/real_world_product_catalog/product_catalog.test.ts
integration/testdata/real_world_product_catalog/schema.keel
runtime/actions/authorization.go
runtime/actions/authorization_test.go
runtime/actions/query.go

Because of how we had implemented permission checking, the following action was NOT authorising correctly.  This has been fixed.
```gql
create createProduct() with (name, barcode, productCode, brand.id) {
@permission(expression: ctx.identity.user in product.brand.editors)
}
```
For larger datasets, we will see a significant performance improvement in the way we check permissions.  Previously we would have seen a major degradation (even to unusable levels).

fix: permission issue on create actions and improved permission performance

---

cron/cron.go
cron/cron_test.go
schema/makeproto.go
schema/testdata/proto_job_scheduled/proto.json
schema/testdata/proto_job_scheduled/schema.keel
schema/testdata/validation_jobs_attributes/errors.json
schema/testdata/validation_jobs_duplicate_inputs_names/errors.json
schema/testdata/validation_jobs_duplicate_names/errors.json
schema/testdata/validation_jobs_schedule/errors.json
schema/testdata/validation_jobs_schedule/schema.keel
schema/validation/duplicate_definition.go
schema/validation/jobs.go
schema/validation/schedule_attribute.go

* Human-readable schedule expressions like **"every 10 minutes"** or **"every monday at 9am"** with strict validation
* Validation for cron-syntax with conversion from unix-style to what EventBridge expects
* Validation that there is only one `@schedule` attribute in a job - we only support one
The following formats are supported:
* `every N minutes`
* `every N minutes from T to T`
* `every N hours`
* `every N hours from T to T`
* `every D at T`
Where `N` is an integer, `T` is a 12-hour time, and `D` is a day. 
In the `every D at T` format both `D` and `T` can be lists of values, for example **"every monday and friday at 9am, 12pm, and 5pm"** produces the cron expression `0 9,12,17 ? * MON,FRI *`. `D` can also be `day` for everyday or `weekday` for MON-FRI.
Cron syntax is still supported …

feat: support human readable schedule expressions and better validation

---

integration/testdata/operation_list_where_explicit/main.test.ts
integration/testdata/operation_list_where_explicit/schema.keel
schema/expressions/scope.go
schema/testdata/proto_expression_named_inputs/proto.json
schema/testdata/proto_expression_named_inputs/schema.keel
schema/testdata/validation_set_attribute_lhs_is_invalid/errors.json

Allow named inputs as LHS operands in expressions
===
Fix to allow named inputs as the LHS operand.  For example:
```
get getPerson(id, n: Text) {
@where(n == person.name)
}
```
However, when used with `@set`, the error message is more appropriate:

fix: named inputs as lhs expression operand

---

cmd/program/client.go

If generated a client with an output dir flag e.g. `-o ../my/frontend` we didn't show the correct output path. 
New output
**Single file client**
```
📦 Generating client SDK..                         
✅ All done!                                       
The following files were generated:                
../customDir/@teamkeel/client/keelClient.ts  
```
**Package client**
```
📦 Generating client SDK..                         
✅ All done!                                       
The following files were generated:                
../customDir/core.ts   
../customDir/@teamkeel/client/index.ts  
../customDir/@teamkeel/client/types.ts  
../customDir/@teamkeel/client/package.ts
```

fix: display full output path when generating a client 

---

commitlint.config.js
integration/testdata/built_in_actions/main.test.ts
integration/testdata/with_custom_function/tests.test.ts
integration/testdata/with_custom_function_hooks/main.test.ts
packages/functions-runtime/src/QueryBuilder.js
testing/testing.go

I was actually trying to fix a different bug but hit this on the way.
Crazy thing was we had a test asserting that it was broken... 🙃

fix: return record or null from findOne method in QueryBuilder

---

cmd/program/commands.go
cmd/program/model.go
config/auth.go
config/config.go
config/config_test.go
config/fixtures/test_auth.yaml
config/fixtures/test_auth_duplicate_names.yaml
config/fixtures/test_auth_invalid_auth_url.yaml
config/fixtures/test_auth_invalid_issuer.yaml
config/fixtures/test_auth_invalid_token_url.yaml
config/fixtures/test_auth_invalid_types.yaml
config/fixtures/test_auth_missing_client_ids.yaml
config/fixtures/test_auth_missing_names.yaml
config/fixtures/test_auth_negative_token_lifespan.yaml
runtime/apis/authapi/token_endpoint_test.go
runtime/oauth/access_token.go
runtime/oauth/access_token_test.go
runtime/oauth/id_token.go
runtime/oauth/id_token_test.go
runtime/oauth/refresh_token.go
runtime/oauth/refresh_token_test.go
runtime/runtime_audit_test.go
runtime/runtimectx/oauth.go

The following can be configured:
- Access and refresh token expiries
- Built-in providers (`google` supported in this PR)
- Custom `oidc` providers for ID token and OAuth authentication
- Custom `oauth` providers for OAuth authentication only
Each type has it's own set of requirements, but all require a `name` and a `clientId`
```yaml
auth:
tokens:
accessTokenExpiry: 3600
refreshTokenExpiry: 604800
providers:
- type: google
name: GoogleClient1
clientId: jjshflsis2ss23
- type: google
name: GoogleAdmin
clientId: 23f223twefgwfw
- type: oidc
name: Auth0
issuerUrl: 'https://dev-skhlutl45lbqkvhv.us.auth0.com'
clientId: 'kasj28fnq09ak'
- type: oauth
name: Github
clientId: hfjuw983h1hfsdf
authorizationUrl: https://github.com/auth
tokenUrl: https://github.com/token
```
If a issuer is not …

feat: keelconfig auth configuration

---

config/auth.go
config/config_test.go
runtime/auth/auth_test.go

Purely a convenience for the backend to add its auth provider (Auth0) when instantiated the runtime.

chore: add oidc provider method

---

node/codegen.go
node/codegen_test.go
node/templates/functions/create.js
node/templates/functions/delete.js
node/templates/functions/get.js
node/templates/functions/list.js
node/templates/functions/types.d.ts
node/templates/functions/update.js

I see this is as a stepping stone to moving most of the function hooks stuff into the functions-runtime package, but I think until the API is 100% stable it's better in codegen as that avoids any issues with version drift between the codegen and the npm package.

chore: refactor some of the sdk codegen for functions

---

functions/functions.go
integration/testdata/functions_http/functions/withHeaders.ts
integration/testdata/functions_http/functions/withQueryParams.ts
integration/testdata/functions_http/functions/withStatus.ts
integration/testdata/functions_http/schema.keel
integration/testdata/functions_http/tests.test.ts
node/bootstrap.go
node/codegen.go
node/codegen_test.go
packages/functions-runtime/src/handleRequest.js
packages/functions-runtime/src/handleRequest.test.js
packages/functions-runtime/src/index.d.ts
runtime/actions/scope.go
runtime/apis/graphql/graphql.go
runtime/apis/graphql/resolvers.go
runtime/apis/httpjson/httpjson.go
runtime/apis/jsonrpc/jsonrpc.go
runtime/common/common.go

This makes it possible to set the HTTP response status from a function. This only has an effect on the HTTP JSON API, for GraphQL and JSON RPC the response status will always be `200`.
```ts
import { MyFunction, permissions } from "@teamkeel/sdk";
export default MyFunction(async (ctx) => {
permissions.allow();
const { response } = ctx;
response.headers.set("Location", "https://some.url");
response.status = 301;
return null;
});
```
In this change I've also dropped the `RequestHeaders` class as I don't think it's necessary. Instead I've updated the types to be a `Headers` object with the mutating methods dropped.

feat: support setting http response status in functions

---

config/auth.go
config/config.go
config/config_test.go
config/fixtures/test_auth.yaml
config/fixtures/test_auth_invalid_redirect_url.yaml
migrations/columns.sql
migrations/migrations.go
runtime/apis/authapi/oauth_endpoint.go
runtime/apis/authapi/oauth_endpoint_test.go
runtime/apis/authapi/token_endpoint.go
runtime/common/common.go
runtime/oauth/auth_code.go
runtime/oauth/auth_code_test.go
runtime/runtime.go

The better thing to do is to redirect from our SSO Login with an authorization code (and not the actual tokens, aka. Implicit Flow, [which is problematic](https://www.taithienbo.com/why-the-implicit-flow-is-no-longer-recommended-for-protecting-a-public-client/)), which can then be traded with access & refresh tokens at the token endpoint - this is standard Authorization Code Flow.  We can also easily extend this with PKCE for customers who need it for their SPA and mobile apps.
In order to use SSO Login, a `redirectUrl` must be configured in `keelconfig.yaml`.
```yaml
auth:
redirectUrl: https://my-keel-application.com/signedin
providers:
- type: google
name: google
clientId: 1234567
```
After authenticating:
Using that code to access tokens:
Needs more tests.  The SSO callback also needs …

chore: using auth code flow

---

cmd/program/commands.go
config/auth.go
config/config.go
config/config_test.go
config/fixtures/test_auth.yaml
config/fixtures/test_auth_invalid_names.yaml
config/fixtures/test_auth_invalid_redirect_url.yaml
go.mod
integration/testdata/jobs_permissions/tests.test.ts
migrations/columns.sql
migrations/migrations.go
runtime/apis/authapi/oauth_endpoint.go
runtime/apis/authapi/oauth_endpoint_test.go
runtime/apis/authapi/response.go
runtime/apis/authapi/revoke_endpoint.go
runtime/apis/authapi/revoke_endpoint_test.go
runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go
runtime/common/common.go
runtime/oauth/auth_code.go
runtime/oauth/auth_code_test.go
runtime/oauth/id_token_test.go
runtime/oauth/oauthtest/oidc_test_server.go
runtime/runtime.go
testhelpers/testhelpers.go

3rd-party "done for you" authentication with our built-in auth providers and any custom OpenID Connect provider.  
In a nutshell:
1. The provider is configured in `keelconfig.yaml` and the client secret added as an env var to the host.
2. The `/auth/login/mygoogleclient` endpoint kicks off the authentication process with the provider named "mygoogleclient" in the keelconfig.yaml.
3. The provider will then request the user authenticate through the necessary means (for example, a username and password page).
4. Upon successful authentication, the provider will callback to Keel, and the handshake will be complete.
5. The identity will be created or updated.
6. The response will be our standard token response (see below).
The response has an identical structure to the token endpoint.  A Keel …

feat: sso login authentication flow

---

config/auth.go
config/config.go
config/config_test.go
config/fixtures/test_auth.yaml
config/fixtures/test_auth_duplicate_names.yaml
config/fixtures/test_auth_invalid_names.yaml
runtime/apis/authapi/authorize_endpoint.go
runtime/apis/authapi/authorize_endpoint_test.go
runtime/apis/authapi/providers_endpoint.go
runtime/oauth/oauthtest/oidc_test_server.go
runtime/runtime.go
testhelpers/testhelpers.go

- Google, Facebook and GitLab built-in support for both flows 🙌
- Reamed `/auth/login` to `auth/authorize` which is far more standard.
- Config provider names with stricter validation as they become a part of URLs and env var names.
- Removed custom `oauth` type.  We will only support custom OpenID Connect for now.
- Not relying on OIDC discovery for endpoints with built-in providers.  Facebook doesn't seem to follow the standard.
```yaml
[
{
"name": "Auth0",
"type": "oidc",
"authorizeUrl": "http://localhost:8000/auth/authorize/auth0",
"callbackUrl": "http://localhost:8000/auth/callback/auth0"
},
{
"name": "google",
"type": "google",
"authorizeUrl": "http://localhost:8000/auth/authorize/google",
"callbackUrl": "http://localhost:8000/auth/callback/google"
},
{
"name": "fb",
"type": …
```

feat: google, facebook and gitlab support & providers endpoints

---

integration/testdata/audit_logs/tests.test.ts
integration/testdata/functions_model_api/main.test.ts
integration/testdata/functions_model_api/schema.keel
integration/testdata/identity_and_authentication/tests.test.ts
integration/testdata/permissions_and_roles/tests.test.ts
integration/testdata/permissions_custom_function/tests.test.ts
integration/testdata/set_backlinks/tests.test.ts
node/codegen.go
packages/functions-runtime/src/ModelAPI.js

This fixes the generation of the unique conditions interface for relationship fields.
As an example the following schema:
```
model Profile {
fields {
name Text
}
}
model Follow {
fields {
from Profile
to Profile
}
@unique([from, to])
}
```
Currently produces a unique conditions interface for `Follow` that looks like this. Both not grouping the `from` and `to` fields into one object, but also using the whole `Profile` model as the type.
```ts
export type FollowUniqueConditions = 
| {from: Profile}
| {to: Profile}
| {id: string};
```
With this fix the unique conditions interface is now this, which correctly groups the fields and uses the id's rather than the whole model.
```ts
export type FollowUniqueConditions = 
| {fromId: string, toId: string}
| {id: string};
```

fix: types for model API with compound unique and findOne

---

config/auth.go
runtime/apis/authapi/authorize_endpoint_test.go

We are fixing the auth provider secret prefer from `KEEL_AUTH_PROVIDER_SECRET_` to `AUTH_PROVIDER_SECRET_`

fix: renaming the client secret name

---

integration/integration_test.go
integration/testdata/functions_hooks/functions/createAuthorAndBooks.ts
integration/testdata/functions_hooks/functions/createBookAndAuthor.ts
integration/testdata/functions_hooks/functions/createBookWithAuthor.ts
integration/testdata/functions_hooks/functions/listBooksBeforeQueryReturnValues.ts
integration/testdata/functions_hooks/main.test.ts
integration/testdata/functions_hooks/schema.keel
integration/testdata/functions_model_api/main.test.ts
integration/testdata/functions_model_api/schema.keel
integration/testdata/real_world_bank_account_app/schema.keel
node/codegen.go
node/codegen_test.go
node/templates/functions/types.d.ts
package-lock.json
packages/functions-runtime/src/ModelAPI.js
packages/functions-runtime/src/tracing.js
schema/validation/errorhandling/errors.go
testing/testing.go

This change means that model inputs for relationships work in `create` functions (as in, they are handled automatically for you) and also that the model API's `create` method supports creating nested records.
Given this schema (permissions omitted)
```
model Author {
fields {
name Text
books Book[]
}
actions {
create createAuthor(name, books.title) @function
}
}
model Book {
fields {
author Author
title Text
}
}
```
And this API request.
```jsonc
// POST /api/json/createAuthor
{
"name": "Emily Bronte",
"books": [
{
"title": "Wuthering Heights"
}
]
}
```
An author record would be created with a linked book record.
Assuming the same schema the same thing can be done with the model API.
```ts
const author = await models.author.create({
name: "Emily Bronte",
books: [
{
"title": "Wuthering …
```

feat: support nested create in functions

---

integration/testdata/functions_http/tests.test.ts
integration/testdata/graphql/main.test.ts
integration/testdata/graphql/schema.keel
integration/testdata/identity_user_organisations/schema.keel
integration/testdata/identity_user_organisations/tests.test.ts
packages/testing-runtime/src/ActionExecutor.mjs
runtime/actions/authorization.go
runtime/actions/authorization_test.go
testing/testing.go

Permissions were blowing up in GraphQL relationships as the scope doesn't contain an action.
The actual fix here though is to remove the inclusion of explicit (`@where`) and implicit (inputs) filters from the permission query. @tomfrew and I discussed this and we feel this is correct.
Fundamentally permissions are _row based_ - meaning you are either **allowed to view a row or not**. By including the action inputs / where conditions you might _sometimes_ be able to view a row and other times not - which is weird.
The updated `identity_user_organisations` test was the only test that failed as a result of removing this, and so I've updated that test.
I've also added a quick graphql integration test - we should build these out to cover all the graphql specific stuff.

fix: bug with permissions in graphql

---

integration/testdata/functions_permissions/functions/createAdmission.ts
integration/testdata/functions_permissions/functions/createUser.ts
integration/testdata/functions_permissions/functions/getUser.ts
integration/testdata/functions_permissions/functions/listUsersByOrganisation.ts
integration/testdata/functions_permissions/main.test.ts
integration/testdata/functions_permissions/schema.keel
permissions/permissions.go
permissions/permissions_test.go

* Updated `permissions` package to support backlinks from `ctx.identity`
* Updated permissions tests
* Added quick integration test for function permissions that uses a backlink
I **strongly** feel that we should update the runtime permissions stuff to use the `permissions` package SQL generation so that we can be sure behaviour is the same between runtime and functions. Looking at the runtime code I don't think this should be too tricky as ultimately we just [execute some SQL](https://github.com/teamkeel/keel/blob/566acda51d3d2e833036e48311d08294f00e4414/runtime/actions/authorization.go#L85)

build: add support for identity backlinks to permissions package

---

cmd/init.go
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml

When init-ing a new project with pnpm you currently get a load of warnings about peer deps missing because the ones we specified were too old.
With the packages updated...
Checked traces locally using the integration tests ands jaeger and they all seem fine.

chore: update functions-runtime otel packags

---

runtime/actions/authenticate.go

Stops recording the token as an attribute in traces

fix: remove token from traces

---

node/scaffold.go
node/scaffold_test.go

Before:
```
import { DoSomething } from '@teamkeel/sdk';
export default DoSomething(async (ctx, event) => {
})
```
After:
```
import { DoSomething } from '@teamkeel/sdk';
// To learn more about what you can do with custom functions, visit https://docs.keel.so/functions
export default DoSomething(async (ctx, event) => {
});
```

fix: improved scaffolding for custom functions

---

.github/workflows/test_npm_modules.yml
packages/functions-runtime/.env.test
packages/functions-runtime/compose.yaml
packages/functions-runtime/src/ModelAPI.test.js
packages/functions-runtime/src/applyAdditionalQueryConstraints.js
packages/functions-runtime/src/handleJob.test.js
packages/functions-runtime/src/handleRequest.test.js

Fixed bug reported by Jay whereby using "ASC" or "DESC" (capitalised) in the ModelAPI's `orderBy` caused a runtime exception.  For example:
```ts
const ascendingNames = await personAPI.findMany({
orderBy: {
name: "ASC",
},
});
```
Resulted in the following:
```
TypeError: expr.toOperationNode is not a function
❯ parseOrderByDirectionExpression node_modules/.pnpm/kysely@0.23.5/node_modules/kysely/dist/cjs/parser/order-by-parser.js:22:21
❯ parseOrderBy node_modules/.pnpm/kysely@0.23.5/node_modules/kysely/dist/cjs/parser/order-by-parser.js:8:92
❯ SelectQueryBuilder.orderBy node_modules/.pnpm/kysely@0.23.5/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:404:145
❯ src/applyAdditionalQueryConstraints.js:13:13
❯ applyOrderBy src/applyAdditionalQueryConstraints.js:12:27
❯ …
```

fix: capitalised asc and desc error in modelapi

---

integration/testdata/functions_http/tests.test.ts
integration/testdata/graphql/main.test.ts
packages/testing-runtime/src/ActionExecutor.mjs
testing/testing.go

I've had to undo [this change](https://github.com/teamkeel/keel/commit/05ee73c1ec0422a121d72397709ff6118ee85fe4) that Jon made as it is breaking `keel test`. We have ZERO testing on `keel test` which makes releasing bugs like this totally likely.
I'd like to see how we can unify the go test and keel test code for integration tests, so that we have less to worry about.  Also, we do need CLI testing.  For now, just fixing the issue.

fix: keel test broken

---

node/client.go

Empty strings are being parsed as invalid dates because the RFC3339 regexp matches on empty strings. So I just changed it to check for truthiness first. You might prefer to adjust the regex instead, but this seems to work well.

fix empty strings being parsed into invalid dates by client js

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/jsonschema_test.go
runtime/jsonschema/testdata/list.json
runtime/jsonschema/testdata/list.keel
runtime/jsonschema/testdata/list_on_related_field.json
runtime/jsonschema/testdata/list_optional_inputs.json
runtime/openapi/testdata/basic.json
runtime/openapi/testdata/optional_fields.json

For ID and String messages, we want to set the json schema to use `oneOf` so that only one of the filters can be used at a time. Tom and I had a chat about this and agreed that we would only do this for ID and String fields for now and only allowing one filter at a time makes sense for both string and id filters.
Looking for feedback on how best to approach this
Attempting to go from:
```
"IdQueryInput": {
"type": "object",
"properties": {
"equals": { "type": ["string", "null"] },
"notEquals": { "type": ["string", "null"] },
"oneOf": { "type": "array", "items": { "type": "string" } }
},
"additionalProperties": false
}
```
to:
```
"IdQueryInput": {
"type": "object",
"oneOf": [
{
"title": "Equals",
"properties": {
"equals": { "type": "string" }
},
"required": ["equals"], …
```

feat: set oneOf json schema property for id and string messages

---

integration/testdata/functions_custom/schema.keel
integration/testdata/functions_http/schema.keel
runtime/actions/authenticate.go
runtime/actions/authorization.go
runtime/actions/authorization_test.go
runtime/actions/create.go
runtime/actions/delete.go
runtime/actions/expression.go
runtime/actions/get.go
runtime/actions/identity.go
runtime/actions/list.go
runtime/actions/query.go
runtime/actions/query_test.go
runtime/actions/scope.go
runtime/actions/update.go
runtime/actions/writeinputs.go
runtime/apis/graphql/graphql.go
runtime/runtime.go
runtime/runtime_audit_test.go

Summary:
- `create`: reduced from 5 to 2 - 5 db hits
- `update`: reduced from 6 to 2 - 4 db hits
- `delete`: reduced from 6 to 2 - 4 db hits
For all action types, we perform better early authorization checks, which means we can avoid unnecessary database hits when row-based permissions aren't being used.  For `create`, we even avoid the use of transactions entirely.
Typically, this is the order of database events (i.e. incurring a DB 'hit') for an built-in `create` action:
a) open transaction
b) execute create statement
c) perform row-based permissions query
d) commit (or rollback) transaction
That is FOUR hits to the database, which is expensive especially when no row-based permissions are even performed.
Now we check if transaction and row-based permission checks are even needed.  If …

perf: smarter transactions and authorization for built-in actions

---

schema/testdata/errors/update_operation_no_unique_lookup.keel
schema/validation/unique_lookup.go

@murej found a case where unique inputs constraint for the update action was not being enforce.  It happened when a unique field was used in `with`. The validation code was not discerning between filter and with inputs correctly.

fix: update action unique input in with only

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/jsonschema_test.go
runtime/jsonschema/testdata/list.json

This change means messages that are enum types (which also have only equals, notEquals and oneOf fields), will also be grouped together in the jsonschema. Previously we were only grouping `StringQueryInput` and `IdQueryInput`, but enums e.g. `Status` would allow you to set all three queries.

Group together all equals, notEquals and oneOf message fields

---

cmd/program/commands.go
migrations/migrations.go
migrations/migrations_test.go
runtime/runtime_audit_test.go
testhelpers/testhelpers.go

Used by the Console/Backend deploy steps to perform a dry run of the database migration early on during the deployment.  This will let us stop the deployment early, before any resources have been updated.
See https://github.com/teamkeel/backend/pull/1108
I think we can tackle this better when we properly looking at how we do migrations. It might be better to rather perform a smarter detection of breaking changes than what I've done here.

build: option to perform dry run database migration

---

runtime/apis/authapi/request.go
runtime/apis/authapi/revoke_endpoint.go
runtime/apis/authapi/revoke_endpoint_test.go
runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go

Previously, only `application/x-www-form-urlencoded` was supported (for OAuth compatibility):
```shell
curl --request POST \
--url 'https://{your-project}.keel.so/auth/token' \
--header 'content-type: application/x-www-form-urlencoded' \
--data grant_type=token_exchange \
--data subject_token={{provider_id_token}}
```
But now we also support `application/json` for convenience:
```shell
curl --request POST \
--url 'https://{your-project}.keel.so/auth/token' \
--header 'content-type: application/json' \
--data '{"grant_type":"token_exchange","subject_token":"{{provider_id_token}}"}'
```

fix: token and revoke endpoints support application json content

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/testdata/arbitrary_function_any.json

Looking into the OpenAPI docs, our previous implementation of the `any` type was not valid.
Updated to use the `anyOf` property as suggested in the docs.

chore: update any type in jsonschema to use anyOf

---

node/client.go
node/client_test.go

The list actions's `pageInfo` property was of type `any`, but it has now been typed properly.

fix: pageInfo typing in typescript client

---

cmd/program/model.go
rpc/rpcApi/schema.go

Fix for bug introduced in https://github.com/teamkeel/keel/pull/1359 which had not been released. The RPC Api's GetActiveSchema was always returning null.

fix: getschemaactive returning null

---

cmd/localTraceExporter/client.go
cmd/localTraceExporter/export.go
cmd/program/model.go
cmd/root.go
cmd/run.go
rpc/rpcApi/context.go
rpc/rpcApi/server.go
runtime/auth/auth.go

* By default only show request traces in the local console
* Use `verbose-tracing` flag for run command to include all system events

build: verbose tracing flag

---

integration/testdata/built_in_actions/main.test.ts
integration/testdata/functions_model_api/main.test.ts
packages/functions-runtime/src/ModelAPI.test.js
packages/functions-runtime/src/index.d.ts

Fix for issue reported here: https://discord.com/channels/1135925644098809907/1135931890621239326/1198899132283236366

fix: notequals for id in modelapi

---

runtime/apis/httpjson/httpjson.go

Errors in tests lack context. Check the issue https://github.com/teamkeel/keel/issues/1371
Propagate errors in a test environment

fix: propagate error messages for httpjson in test environment

---

cmd/program/model.go
rpc/rpcApi/context.go
rpc/rpcApi/server.go

When using the local Console we are getting failed token requests because the Console's auth provider has not been configured in the customer's keelconfig.yaml.  We therefore add this to the configuration.  Note that we are only adding it for ID Token authentication and therefore no client secret is required.

fix: add console auth provider on cli

---

cmd/program/commands.go
cmd/program/model.go
cmd/run.go
compose.yaml

Local Console monitoring was not yet capturing functions runtime tracing.  This PR will ensure that all traces are captured.
Also renamed the tracing flag to `custom-tracing`, which feels more appropriate.  Enabling this flag with disable Keel tracing and let you run your own OTEL receiver on localhost:4318

fix: local tracing for functions runtime

---

schema/completions/completions.go
schema/completions/completions_test.go

Intended for use by the VS Code extension.
Suggests `actions` in an opened model block:
```
api MyApi {
models {
Author {
<<--  actions
}
}
}
```
Suggests action names in an opened actions block:
```
api MyApi {
models {
Author {
actions {
<<-- getAuthor, createAuthor, etc.
}
}
}
}
```

fix: api model action code completions

---

cmd/program/commands.go
cmd/program/model.go
config/auth.go
config/config.go
config/config_test.go
config/fixtures/test_auth_reserved_prefix.yaml
runtime/apis/authapi/providers_endpoint.go

- The CLI is setup with Keel's auth providers for Local Console support
- `keel_` prefix now reserved for provider names (validation included)
- `keel_`  providers omitted from `/auth/providers/` response

chore: setup keel console auth providers

---

cmd/init.go

When running `keel init`, the keelconfig now generates to this:
```
auth:
environment:
secrets:
```

chore: keelconfig includes auth section on keel init

---

rpc/rpcApi/server.go

The CLI's RPC API exposes endpoints for use by the Local Console.  The `ListTraces` endpoints now filters traces by the "error" filter.

fix: error filtering for local console monitoring

---

runtime/actions/authenticate.go
runtime/actions/identity.go
runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go
runtime/runtime_audit_test.go

The `/auth/token` endpoint now supports the [password grant](https://www.oauth.com/oauth2-servers/access-tokens/password-grant/).  It behaves in much the same way as the legacy `authenticate()` action.
We have decided to support the password grant flow.  Even though it comes with its flaws, it does allow users to get up and running very quickly.  We can discourage its use in the docs in favour of the ID Token or SSO flows.

feat: password grant

---

.github/workflows/create_release.yml
.github/workflows/npm_release.yml
.github/workflows/semantic_release.yml
.goreleaser.yaml
.releaserc
go.mod
go.sum
packages/keel/package.json
packages/keel/pnpm-lock.yaml
packages/keel/scripts/setup.js

We are moving away from Homebrew to using NPM as the package manage for the Keel CLI.  This pull request sets the foundation for this with some major changes to our release processes.
- Better use of semantic release and a `.releaserc` config.
- Prerelease branches `next` and `prerelease` with appropriate versioning (e.g. `0.377.2-prerelease.1`).
- Cleaned up Goreleaser and reworked it not to release to Homebrew.
- Go binaries now as release artifacts in this repository (and not in teamkeel/cli anymore).
- Keel NPM package.  The package is smart and will only retrieve the platform-dependency binaries from GitHub release during an `npm install`.

build: keel on npm

---

.github/workflows/semantic_release.yml

Latest semantic version requires >=v20 of node.  Also fixed semantic-version to v23 so that future build do not unexpectently fail.

fix: semver action node version

---

.github/workflows/release.yml

Only release Go binaries and NPM packages when semantic release detects a new version increment.

build: dont run release when no version increment

---

README.md
packages/keel/README.md

Second attempt at fixing our logo image in the NPM registry readme.

fix: npm readme logo again

---

cmd/init.go

Previously, this would occur when choosing not to initialise git.  In fact, any entry other that y/Y would cause this panic.  With this fix, any entry other than y/Y will be regarded as n/N.

fix: keel init panic when choosing not to git init

---

cmd/program/commands.go
cmd/program/model.go
cmd/program/views.go
go.mod
go.sum

When a newer version is available on the `latest` distribution channel on NPM, then the following message is shown:
Note that this check is asynchronous and will fail silently if something goes wrong.
Also improved the API endpoint sections:

fix: check for cli updates

---

integration/testdata/client_auth/keelClient.ts
integration/testdata/client_password_grant/keelClient.ts
integration/testdata/client_password_grant/keelconfig.yaml
integration/testdata/client_password_grant/main.test.ts
integration/testdata/client_password_grant/schema.keel
node/client.go
node/client_test.go
node/templates/client/core.ts
node/templates/client/types.d.ts
runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go
testing/testing.go

This is based on ongoing work with @TejasQ 
- Added password flow auth
- Refresh and access tokens are not storable.
- Changed the API to get and set tokens.
- Improved the refresh flow
- Added some much needed tests
Not done is returning the identity when authenticating.  This will probably require us either to create a OIDC user-info endpoint or to return an ID token from the token endpoint with all the necessary user claims, which we can then parse properly in the client.

fix: client token refresh improvements

---

runtime/apis/authapi/openapi_definition.go

This should fix the issue we have when translating the openapi auth schema to a form for authenticating in the API explorer.

chore: update auth openapi definition for token request

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/jsonschema_test.go
runtime/jsonschema/testdata/list.json

Updates the remaining input query messages using either `oneOf` or `anyOf` options in the open api schema.
- `BooleanQueryInput` message is now set to use `oneOf`
- `DateQueryInput`, `TimestampQueryInput` and `IntQueryInput` now use `anyOf` - this is so that we can allow group these inputs together in the Console Tools UI, but also allow more than one of their filters to be set.

fix: add BooleanQueryInput to oneOf conditions and create anyOf grouping

---

node/templates/client/core.ts

Using `atob` to decode the JWT instead of `Buffer` will mean the generated client can be used in the browser.

fix: add browser support to generated auth client

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/jsonschema_test.go
runtime/jsonschema/testdata/list.json

Currently `anyOf` options are set to have `additionalProperties: false` which stops the client from sending a request with multiple filters.

fix: allow additionalProperties on anyOf options

---

runtime/jsonschema/jsonschema.go
runtime/jsonschema/testdata/list.json

this fixes issues we are having with react-json-schema-form and `additionalProperties: true`. Removing this completely still means we can pass any of the `anyOf` filter options to the request so it is not required.

fix: don't set additionalProperties for anyOf options

---

runtime/apis/authapi/openapi_definition.go
runtime/jsonschema/jsonschema.go

This change is required for when we use the open api schema, we can hide the `grant_type` input field from showing in the UI, as a default value (the const) is already set.

fix: update auth openapi schema with default value

---

integration/testdata/identity_and_authentication/tests.test.ts
runtime/apis/authapi/openapi_definition.go
runtime/apis/authapi/revoke_endpoint_test.go
runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go

By setting the `create_if_not_exists` to `false` on the token endpoint, the identity will not be created if it does not exist yet.  
This parameter is optional.  The default is `true`.
This is supported for the Password and ID Token flows.
The token endpoint now includes the field `identity_created` in the response body which informs whether an identity was created or not during the auth operation.

feat: registration and login flows with identity with password and id token auth

---

cmd/program/commands.go

When running git commands in a Keel project directory (or any subpath for that matter), keel run will refresh by reloading and starting up the project again. This PR addresses this issue by ignoring the `.git` folder form the watched files.

fix: ignore .git folder from hot reloading when running `keel run`

---

cmd/database/database.go
cmd/localTraceExporter/client.go

When pummeling the local CLI running Keel with lots of events, I am able to produce the following panic in the local trace exporter:
```
fatal error: concurrent map read and map write
```
This is because we're concurrently reading and writing to a dictionary.  The fix just includes moving the mutex up.

fix: concurrent map reads on upload trace

---

auditing/auditing.go
events/events.go
integration/testdata/events_basic/subscribers/verifyUpdate.ts
migrations/migrations.go
node/codegen_test.go
runtime/runtime_events_test.go
schema/makeproto.go
schema/testdata/proto/attribute_on/proto.json

The event payload for update and delete events types now include the full state of the model _before_ the mutation which triggered the event.  
For example, this is what the definition would look like for an event on a `create` and `update` action:
```ts
export type VerifyEmailEvent = (VerifyEmailMemberCreatedEvent | VerifyEmailMemberUpdatedEvent);
// Note that the create event target does NOT include previousData
export interface VerifyEmailMemberCreatedEvent {
eventName: "member.created";
occurredAt: Date;
identityId?: string;
target: VerifyEmailMemberCreatedEventTarget;
}
export interface VerifyEmailMemberCreatedEventTarget {
id: string;
type: string;
data: Member;
}
// Note that the update event target DOES include previousData
export interface VerifyEmailMemberUpdatedEvent { …
```

feat: previous state in event payload

---

cmd/client.go
cmd/generate.go
cmd/run.go
cmd/secrets.go
cmd/test.go
cmd/validate.go

Consolidate CLI commands arguments validation by enforcing the required number of args; e.g:
```
user@pc> keel secrets remove 
Error: accepts 1 arg(s), received 0
Usage:
keel secrets remove <key> [flags]
...
```
```
user@pc> keel run project  -d ./../starter
Error: unknown command "project" for "keel run"
Usage:
keel run [flags]
...
```
```
user@pc> keel secrets set TEST "value" dev
Error: accepts 2 arg(s), received 3
Usage:
keel secrets set <key> <value> [flags]
```

chore: enforce correct number of args for each command

---

schema/testdata/errors/actions_no_bare_model_as_input.keel
schema/testdata/errors/unique_input_bare_model.keel
schema/validation/rules/actions/actions.go

The error message should say “which cannot **be** used as an input” instead.

fix: typo in error message

---

packages/testing-runtime/src/Executor.mjs

The testing SDK (i.e. `await actions.createThing(...)`) is not correctly parsing date and timestamp values which have no millisecond component.  For example, `2024-02-01T00:00:00Z` would be parsed as a string and not a `Date`.  I have now made the millisecond component optional in the reviver.

fix: dates without ms not parsed in test sdk

---

integration/integration_test.go
integration/testdata/audit_logs/tests.test.ts
integration/testdata/events_basic/subscribers/verifyUpdate.ts
integration/testdata/permissions_delete_operation/tests.test.ts
integration/testdata/permissions_get_operation/tests.test.ts
integration/testdata/permissions_list_operation/tests.test.ts
integration/testdata/set_backlinks/tests.test.ts
runtime/actions/delete.go

* Re-enabling the complete integration test suite. 
* Fixing a few typos in some integration tests.
* Fixing an issue which caused unexpected errors for `delete` actions that would require row based permission checks.

fix: issue affecting `delete` actions with row based permission checks & re-enable all integration tests

---

integration/testdata/arrays/tests.test.ts
node/codegen_test.go
runtime/actions/list.go
runtime/actions/operator.go
runtime/actions/query.go
runtime/actions/query_test.go
runtime/apis/graphql/testdata/graphql/arrays.graphql
runtime/openapi/testdata/arrays.json
schema/makeproto.go
schema/testdata/proto/array_fields/proto.json

With the `list` action, it is now possible to perform queries within array data using the `all` and `any` query operators.  For example, the following query returns all posts **where any tag is equal to "science"**:
```gql
query {
listPosts(input: {
where: {
tags: {
any: {
equals: "science"
}
}
}
}) {
...
}
}
```
All of the scalar query operations are available, with the exception of `contains`, `startsWith` and `endsWith` for Text.
It is also possible to combine queries in just the same way with our existing list querying.  For example:
```gql
query {
listPosts(input: {
where: {
tags: {
any: {
equals: "science",
notEquals: "education"
},
all: {
notEquals: "science"
}
}
}
}) {
...
}
}
```
This will be generated into a single SQL query.  And, of course, you can combine this with …

feat: array any and all queries

---

schema/testdata/errors/fields_names_max_lenght.keel
schema/testdata/errors/model_names_max_lenght.keel
schema/validation/errorhandling/errors.go
schema/validation/errorhandling/errors.yml
schema/validation/rules/field/field.go
schema/validation/rules/model/model.go
schema/validation/validation.go

Postgresql has a maximum identifier length limit of 63 bytes. Anything over 63 bytes will be automatically truncated and this will cause issues with migrations. 
This PR adds validation rules to check that field names and model names will not create identifiers longer than the limit enforced by the DB engine. The limit is applied on the snake cased version of the field/model name, as this is what will be used in order to generate the db identifiers. The limit also takes in account the longest suffix added to generated triggers (e,g, `model_name_updated_at`).

feat: enforce maximum identifier length through validation rules

---

integration/testdata/client_basic/main.test.ts
integration/testdata/client_basic/schema.keel
packages/functions-runtime/src/ModelAPI.js

When creating models via ModelAPI, all fields need to be passed through the snake case object helper func. This will transform fields such as `address1` into the expected db column `address_1`.

fix: snake case fields when creating via ModelAPI

---

cmd/database/database.go

I've found that I am regularly getting the following error when running `keel` locally:
```
Error: failed to connect to `host=0.0.0.0 user=postgres database=`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
Usage:
keel test [flags]
Flags:
-h, --help                      help for test
-p, --pattern string            pattern to isolate test (default "(.*)")
--private-key-path string   path to the private key .pem file
Global Flags:
-d, --dir string   directory containing a Keel project (default "/Users/davenewza/code/keel/integration/testdata/client_password_grant")
-v, --version      Print the Keel CLI version
Error: failed to connect to `host=0.0.0.0 user=postgres database=`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
```
Adjusting …

fix: database connect timeout too short

---

schema/format/format.go
schema/format/testdata/repeated_field.txt
schema/format/writer.go

Optional repeated fields, defined as `Type[]?` are automatically formatted to `Type?[]` which is not a valid definition. This PR addresses this issue by moving the optional `?` char after the array notation `[]`.
Also, this PR moves the writer structure in a new file and un-exports its methods as they are not used outside of the `format` package

Format optional repeated fields 

---

cmd/program/commands.go
cmd/program/model.go
cmd/program/views.go
cmd/root.go
cmd/run.go

It may be necessary to make the local Keel application available on some custom domain, such as with using ngrok.
It will then be necessary to configure Keel accordingly, especially because SSO requires redirects back to the Keel app, which will now need to be aware of this custom hostname.
Use `--hostname` to configure this:
```
keel run --hostname https://mycustomdomain
```
The CLI will then expose URLs and redirects using this hostname.

feat: custom hostname for `keel run`

---

cmd/database/database.go

Pointing to a new Docker volume for the upgrade to PostgeSQL 16.  This will maintain customer's existing data on the old volume, and it will mean they can revert back to a previous version of Keel to access it.  They can also migrate if need be.

fix: using new volume for pg16

---

colors/colors.go
packages/wasm/index.d.ts
packages/wasm/index.test.ts
packages/wasm/lib/main.go
packages/wasm/lib/wasm_exec_node.js
schema/schema.go
schema/validation/errorhandling/errors.go
schema/validation/errorhandling/format.go
schema/validation/studio_features.go
schema/validation/validation.go

Validation errors will now include warnings. These are suppressed by default when using the CLI but in the wasm package an option is available which will include warnings in its output. The WASM validation will now also just validate rather than build the proto schema. This will inevitably improve performance, but it is unknown by how much at this point in time.

Feat: validation improvements & WASM update

---

config/config.go
config/fixtures/test_basic_config.yaml

The following validation error was occurring, which is incorrect:

fix: numbers in secret names

---

runtime/runtime.go

Request and response logging was added previously (see https://github.com/teamkeel/keel/pull/785) but the request data was never really logged, only the response. This PR fixes this issue and will create two log entries, one for the request and one for the response. The response log will also contain the request url.

fix: request/response logging

---

runtime/runtime.go

Runtime logging level should be controlled via a dedicated `KEEL_` prefixed env var to avoid collisions with other env vars that may be used in custom code.

fix: rename runtime logging env var

---

auditing/auditing.go
events/events.go

It is possible for the event_processed_at column on the `keel_audit` table to not be set when parsing audit logs.  It could be unset due to a legitimate race condition or if an event was not set up for that op type at that time.
We don't need to even parse this column anyway, so I am removing it.

fix: audit 'event_processed_at' column cannot be parsed or is empty

---

config/auth.go
config/config_test.go
config/fixtures/test_auth_identity_claims.yaml
integration/testdata/identity_claims/keelconfig.yaml
integration/testdata/identity_claims/schema.keel
integration/testdata/identity_claims/tests.test.ts
schema/schema.go

By default, the Identity fields `email` and `issuer` form a composite unique constraint.  However, it may be possible that additional fields need to be included in that constraint.  In particular, claims from the 3rd party provider's token.  An example of this would be "team ID".
To include a claim, simply set `unique: true` in the keelconfig:
```yaml
auth:
providers:
- type: google
name: google
clientId: 123456
claims:
- key: https://slack.com/#team_ID
field: teamId
unique: true
```

feat: custom unique fields on identity claims

---

schema/testdata/errors/attribute_unique.keel
schema/validation/unique_attribute.go

Schema validation now catches the use of strings in `@unique` and provides appropriate validation errors.

fix: validation for string args in @unique

---

cmd/root.go
cmd/validate.go

Using the `--json` flag on `keel validate` will output JSON formatted schema and config validations.

fix: json output format from keel validate

---

cmd/root.go
cmd/validate.go
config/config.go
config/config_test.go

Allow passing of Keel schema and config as arguments on CLI's validate action.  For example:
`keel validate --schema "model Thing{}" --config "auth:"`
This is necessary for the VS Code extension to be able to validate unsaved changes.

fix: pass keel schema and config as cli args on validate

---

packages/wasm/index.d.ts

WASM's `ValidationRequest.includeWarnings` Incorrectly defined as `bool`

fix: boolean in wasm definition

---

schema/format/format.go
schema/format/testdata/job_inputs.txt

When formatting job inputs, `ID` is a valid type but the formatter was CamelCasing it to `Id`. This small PR fixes this issue

fix: formatter issue when using IDs in job input types

---

cmd/validate.go

Opting to rather using base64 for `--schema` and `--config` CLI arguments

fix: cli schema and config args to use base64

---

cmd/program/views.go
cmd/validate.go

When running `keel validate` we do not need to render any warnings since at the moment warnings are not fully used in a cli environment.

fix: remove warnings from validate cli output

---

schema/completions/completions.go
schema/completions/completions_test.go

Adding completions for `@embed` attributes. The completions will be reduced to a set of model fields (relationships) available on the given model.

fix: add completions for embed attributes

---

integration/testdata/embedded_data/main.test.ts
node/codegen.go
node/codegen_test.go
runtime/actions/get.go
runtime/actions/list.go
runtime/jsonschema/jsonschema.go
runtime/openapi/testdata/embedded_data.json

When embedding a related object, we want to remove the foreign key; i.e.:
```
actions {
list listBooks() {
@embed(author)
}
}
```
```
"results": [
{
"author": {
"createdAt": "2024-06-24T12:49:02.765243Z",
"firstName": "Radu",
"id": "2iKJTcMSCRsnNA1ifJSQkZ7Kl8d",
"surname": "Gruia",
"updatedAt": "2024-06-24T12:49:02.765243Z"
},
"authorId": "2iKJTcMSCRsnNA1ifJSQkZ7Kl8d",   <=== This should be removed from responses
"createdAt": "2024-06-24T12:49:13.964459Z",
"id": "2iKJV1XbGfE7DhzCxS6gSuP8mK2",
"title": "A book",
"updatedAt": "2024-06-24T12:49:13.964459Z"
}
]

feat: remove foreign key from schema when object is embedded

---

functions/functions.go
integration/testdata/functions_auth_hooks/schema.keel
runtime/apis/authapi/authorize_endpoint.go
runtime/apis/authapi/token_endpoint.go

- The `afterIdentityCreated` hook now executes before the `afterAuthentication`
- Errors in hook functions now cause the request to error

fix: afterIdentityCreated occurs before afterAuthentication

---

runtime/actions/file_uploads.go

When attempting to transform json data from the db representing inline file data, we should be skipping null entries

fix: skip transforming null inline files json data

---

runtime/actions/embed.go
runtime/jsonschema/jsonschema.go
runtime/openapi/testdata/embedded_data.json
runtime/openapi/testdata/embedded_data.keel

Removing the id field of an embedded relation: e.g.
when embedding `author` for a `Book`, remove `authorId` from returned response. This fix ensures that the id field is removed even when the field is related to a different type of Model (e.g. `author` is of type `User` instead of `Author`)

fix: remove embedded field's ID from jsonschema

---

packages/functions-runtime/src/parsing.js
packages/functions-runtime/src/parsing.test.js

When converting `InlineFile` inputs (for jobs inputs & subscriber messages etc), parse nested messages as well; This will support inputs such as: 
```
message FileInput {
image InlineFile
name Text
}
message NestedFileInput {
file FileInput
anotherImage InlineFile
}
```

fix: parse nested inputs when converting InlineFiles

---

runtime/jsonschema/jsonschema.go
runtime/openapi/openapi.go
runtime/openapi/testdata/job.json
runtime/openapi/testdata/job.keel

When defining InlineFiles as inputs to jobs & custom functions, the openapi schema generated must be a string with format: `data-url`

fix: inline files used in input messages to jobs & custom functions 

---

node/codegen.go
node/codegen_test.go

When embedding files, the js sdk generated types must remove the foreign key, regardless of the naming of the field: i.e. 
```
fields {
city City
birthplace City
}
```
will need both `cityId` and `birthplaceId` removed if they are embedded

fix: fix generated client types for embeds

---

integration/testdata/embedded_data/main.test.ts
integration/testdata/embedded_data/schema.keel
runtime/actions/embed.go

A bug prevented embeds with relationships from the same model. This PR addresses it by joining the source model with an alias. The following embed will now work as intended
```
model Post {
fields {
title Text
parent Post?
}
actions {
list listPosts() {
@embed(parent)
}
}
}
```

fix: allow embeds from same model

---

integration/testdata/headers/functions/createPersonUsingHook.ts
integration/testdata/headers/functions/writePersonUsingCustomFunc.ts
integration/testdata/headers/schema.keel
integration/testdata/headers/tests.test.ts
runtime/expressions/operand.go

Because the Keel schema does not support dashes well, we have opted to represent canonical kebab style header names in Pascal case in expressions.
For example, if the header provided into the request is `My-Data-Key`, then that header can be resolved in expressions with `ctx.headers.MyDataKey`.
Note that headers are case insensitive.  Also, Keel does not support headers with underscores (as with NGINX, these are dropped by default)

fix: pascal case headers in schema

---

integration/testdata/headers/schema.keel
integration/testdata/headers/tests.test.ts

Test case with a x-prefixed header such as `X-Api-Key`

test: header tests with x prefix

---

runtime/actions/parsing.go
runtime/actions/parsing_test.go
runtime/actions/scope.go
runtime/runtime.go

Reusing the `InlineFile` transform function in the job handler.

fix: reuse inlinefile transform function in jobs

---

functions/functions.go
integration/testdata/events_basic/tests.test.ts
integration/testdata/functions_errors/functions/badRequest.ts
integration/testdata/functions_errors/functions/hookNotFound.ts
integration/testdata/functions_errors/functions/hookNotFoundCustomMessage.ts
integration/testdata/functions_errors/main.test.ts
integration/testdata/functions_errors/schema.keel
integration/testdata/functions_hooks/main.test.ts
integration/testdata/jobs_permissions/tests.test.ts
integration/testdata/subscribers_basic/tests.test.ts
node/codegen.go
node/codegen_test.go
node/templates/functions/types.d.ts
packages/functions-runtime/src/errors.js
packages/functions-runtime/src/handleJob.test.js
packages/functions-runtime/src/handleRequest.js
packages/functions-runtime/src/handleRequest.test.js
packages/functions-runtime/src/index.d.ts
packages/functions-runtime/src/index.js
runtime/actions/delete.go
runtime/actions/update.go
runtime/common/common.go

* Export an `errors` object from the functions SDK with error classes which can be used to throw specific error types which when get transforms into the correct status codes in the response by the runtime
* Uses `ERR_UNKNOWN` instead of `ERR_INTERNAL` for general errors in the function to separate core runtime errors from user code errors
```typescript
import { errors } from "@teamkeel/sdk";
export default CustomFunction(async (ctx, inputs) => {
throw new errors.NotFound("custom message"); // Returns a 404 with the standard runtime error strcuture
}
```

feat: functions-runtime errors

---

.github/workflows/go.yml
cmd/program/views.go
db/gorm.go
integration/testdata/arrays_relationships/schema.keel
integration/testdata/arrays_relationships/tests.test.ts
integration/testdata/functions_use_database/main.test.ts
node/node.go
runtime/actions/authorization.go
runtime/actions/delete.go
runtime/actions/expression.go
runtime/actions/get.go
runtime/actions/identity.go
runtime/actions/list.go
runtime/actions/query.go
runtime/actions/query_test.go
runtime/actions/update.go
runtime/actions/writeinputs.go
runtime/apis/graphql/graphql.go
runtime/openapi/openapi_test.go
schema/makeproto.go
schema/query/query.go
storage/database_storer.go

In expressions, the `in` and `not in` operators can now be used to against array field operands.  For example:
```
list suggestedBooks() {
@where(book.genre in ctx.identity.person.favouriteGenres) // 1:1 relationship between identity and person
@orderBy(title: asc)
@permission(expression: true)
}
```
And even in cases like this, where the arrays will be squashed:
```
list suggestedBooks() {
@where(book.genre in ctx.identity.friends.favouriteGenres) // 1:M relationship between identity and person
@orderBy(title: asc)
@permission(expression: true)
}
```

fix: in operator using array operands

---

events/events.go
migrations/migrations.go
migrations/sql.go
node/client.go
node/codegen.go
node/scaffold.go
permissions/permissions.go
proto/action.go
proto/field.go
proto/message.go
proto/model.go
proto/model_test.go
proto/query.go
proto/query_test.go
proto/schema.go
proto/schema_test.go
runtime/actions/embed.go
runtime/actions/expression.go
runtime/actions/query_test.go
runtime/actions/writeinputs.go
runtime/apis/graphql/graphql.go
runtime/apis/httpjson/httpjson.go
runtime/apis/jsonrpc/jsonrpc.go
runtime/expressions/operand.go
runtime/jsonschema/jsonschema_test.go
runtime/openapi/openapi.go
runtime/runtime_audit_test.go
runtime/runtime_events_test.go
runtime/runtime_rpc_test.go

Housekeeping update of the proto package:
Duplicated most functions as methods on their respective structures; e.g. `func (f *Field) IsHasMany() bool` instead of ` func IsHasMany(field *Field)` and deprecated original functions. Migrate all usage of newly deprecated function to the new definitions. 
Split the methods across multiple smaller and easier to follow files relevant to the receiver of the method (e.g. `model.go`, `field.go` etc. )

chore: refactor proto query

---

.golangci.yml
events/events.go

Re-enabling staticcheck. Update trace check for noop to use new package

chore: re-enable staticcheck linter. update deprecated method

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/functions-runtime/src/database.js

- Ditching the neon-kysely dialect for the neon/serverless client
- Connection timeout value based on KEEL_DB_CONN_TIMEOUT or set to 45s
- Monkey patching the serverless client for our tracing needs
- Log the pg/neon dialect and timeout in db spans

fix: js database connection timeout and serverless driver

---

runtime/actions/file_uploads.go
storage/storage.go

This change prevents the presigned URL from being stored in the database.  The presigned URL is generated every time we include a `Feel` field within an API response, so it doesn't need to be stored.  Plus, it will expire anyway.

fix: do not store file url

---

runtime/actions/create.go
runtime/actions/update.go

When no files exist on a model, there is no reason to run `handleFileUploads`.  Also, this was causing a runtime error in the hosted environment.

fix: ignore file handling when no files on model

---

runtime/actions/query.go
runtime/actions/query_test.go

When performing an `update` which requires checking conditions on related tables, we need to ensure that we are left joining on those tables.  The reason for this is because if there is no relationship present, then we don't want the row to be omitted.
However, we have been using `FROM` in our update statements.  When relationships are involved, will are now using sub-queries.  This is cleared to understand and fixes the issue.  
Except from Postgres docs: 
> When a FROM clause is present, what essentially happens is that the target table is joined to the tables mentioned in the from_item list, and each output row of the join represents an update operation for the target table. When using FROM you should ensure that the join produces at most one output row for each row to be modified. In …

fix: updates to left join on relationships

---

node/codegen.go
node/codegen_test.go

The `SortDirection` type from the functions runtime was not being referenced correctly.

fix: sort direction type resolution

---

tools/generator.go
tools/testdata/blog/tools.json

The list action `results` property not correctly marked as repeated in tools config

fix: gen tools repeated for list action

---

integration/testdata/files/tests.test.ts
runtime/actions/create.go
runtime/actions/files.go
runtime/apis/graphql/types.go
runtime/jsonschema/jsonschema.go
runtime/openapi/testdata/basic.json
runtime/openapi/testdata/files.json
schema/testdata/proto/message_file_field/proto.json
schema/testdata/proto/message_file_field/schema.keel
storage/database_storer.go
storage/storage.go

File's `url` response field now required in jsonschema.  Removed `public` field from the GraphQL schema.

fix: files url in jsonschema, removed public field from graphql, minor refactoring

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/nested_inputs/tools.json

We were changing the display name to remove the `ID` suffix only if there was a linked action for the given response field, to retrieve the item by ID. This PR will trim the ID from display names regardless of wether there's a action link for that response or not.

chore: update display name for foreign key fields

---

runtime/actions/query.go
runtime/actions/query_test.go

PostgreSQL reserved keywords can now be used in the schema without risk of breaking any underlying SQL generation.  This was already the case for retrieving data using `get` and `list` actions, but now has been also fixed for `create` and `update`.

fix: sql keyword escaping for create and update actions

---

packages/functions-runtime/src/database.js

Limiting the number of connections in the functions runtime to 1.  Furthermore, configuring 3 retries with an interval of 1s.

fix: functions database connection limit and retries

---

integration/testdata/audit_logs/tests.test.ts
integration/testdata/events_basic/tests.test.ts
integration/testdata/jobs_permissions/tests.test.ts
integration/testdata/subscribers_basic/tests.test.ts
node/codegen.go
node/codegen_test.go
packages/functions-runtime/src/auditing.test.js
packages/functions-runtime/src/database.js
packages/functions-runtime/src/handleJob.js
packages/functions-runtime/src/handleRequest.js
packages/functions-runtime/src/handleSubscriber.js
packages/functions-runtime/src/index.d.ts
packages/functions-runtime/src/tryExecuteFunction.js
packages/functions-runtime/src/tryExecuteJob.js
packages/functions-runtime/src/tryExecuteSubscriber.js

We currently wrap all mutation functions in a transaction which gets rolled back if the function throws an error. This is a great default but there are times where you do want to write to the db and also return an error. This PR adds optional configuration to our generated function wrappers which would enable users to control the behaviour of the functions runtime. And then uses this config to control the automatic transaction behaviour
e.g.
```ts
MyFunction.config = {
autoTransaction: false,
};
export default MyFunction(async (ctx, inputs) => {
// .. do things
});
``` 
or for hooks
```ts
const hooks: MyFunctionHooks = {
beforeWrite: async (ctx, inputs, values, record) => {
// ..do things
},
};
MyFunction.config = {
autoTransaction: false,
};
export default MyFunction(hooks);
```

feat: function configuration for auto transactions

---

cmd/validate.go
config/schema.json

`keelconfig.yaml` errors are now not sent to stderr when calling `keel validate --json`.  This is important for the VSCode extension as any stderr  in `--json` mode is recognised as a CLI failure.
Furthermore, relaxing the config schema rules to allow empty (null) values for the root level `secrets:`, `auth:` and `environment:` properties. These are generated as so by `keel init` and so this would be a breaking change otherwise.
@jonbretman FYI - hope this makes sense

fix: dont stderr for config errors with --json flag set

---

cmd/validate.go
schema/schema.go

If a `keelconfig.yaml` validations exist, any schema validation errors weren't being returned in `--json` mode.  @jonbretman FYI

fix: dont swallow schema validation when config has errors

---

integration/testdata/audit_logs/tests.test.ts
integration/testdata/events_basic/tests.test.ts
integration/testdata/jobs_permissions/tests.test.ts
integration/testdata/subscribers_basic/tests.test.ts
packages/functions-runtime/src/database.js
packages/functions-runtime/src/tryExecuteJob.js
packages/functions-runtime/src/tryExecuteSubscriber.js

Undoing the change made #1615 where jobs and event subscribers have transactions enabled by default

fix: disabling transactions for jobs and event subscribers

---

schema/format/format.go
schema/format/testdata/api_with_actions.txt

The formatter (used by the VSCode extension) will now correctly format the `api` sections in the Keel schema.  For example:
```
api Api {
models {
// Something or other
Author
Post {
actions {
getPost
listPosts
}
}
Category {
actions {
// Something or other
listCategories
}
}
}
}
```

fix: keel schema api formatting

---

config/config.go
config/fixtures/test_auth.yaml
config/fixtures/test_auth_invalid_auth_url.yaml
config/fixtures/test_auth_invalid_token_url.yaml

`tokenUrl` and `authorizationUrl` are not required for `oidc` auth type due to the auto discovery nature of OpenID Connect.

fix: relaxed requirement on token and auth url in keelconfig

---

packages/functions-runtime/src/database.js

Numeric support for the neon driver.  See https://kysely.dev/docs/recipes/data-types#configuring-runtime-javascript-types

fix: decimal type for neon driver

---

schema/completions/completions.go
schema/completions/completions_test.go

`@embed` was previously not included in code completions for attributes within a action block. This now fixes the issue.

fix: add embed attribute to code completions

---

schema/schema_test.go
schema/testdata/errors/attribute_embed.keel
schema/testdata/errors/attribute_orderby_invalid_args.keel
schema/testdata/errors/attribute_unique.keel
schema/testdata/errors/attribute_unique_invalids_args.keel
schema/testdata/errors/jobs_permission_attribute_expression_invalid_args.keel
schema/testdata/errors/jobs_permission_attribute_role_invalid_args.keel
schema/testdata/errors/jobs_schedule.keel
schema/testdata/errors/operation_where_too_many_arguments.keel
schema/testdata/errors/permission_action.keel
schema/testdata/errors/permission_attribute_invalid_args.keel
schema/testdata/errors/permission_job.keel
schema/testdata/errors/relationships_attr_empty.keel
schema/validation/attribute_arguments.go
schema/validation/errorhandling/errors.go
schema/validation/errorhandling/errors.yml
schema/validation/orderby_attribute.go
schema/validation/permission_attribute_arguments.go
schema/validation/rules/attribute/attribute.go
schema/validation/schedule_attribute.go
schema/validation/validation.go

Moving the basics around attribute argument validation to one place.  Any special rules for an attribute still remain in their place.  Also improved the hint responses. 
I do think we can expand on this a lot more.  I will likely do so in the CEL work.

chore: attribute argument validations

---

.github/workflows/go.yml
.github/workflows/test_npm_modules.yml
node/codegen.go
node/codegen_test.go
packages/client-react-query/package.json
packages/client-react-query/pnpm-lock.yaml
packages/client-react/package.json
packages/client-react/pnpm-lock.yaml
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml

* Set `pnpm` version via `packageManager` field
* Update Github Actions to use this and Node 22.11
* Update generated server.js file to use commonjs - latest node is stricter about ES Modules

chore: support node 22.11 (lts)

---

node/templates/client/core.ts

* In the generated client, try to get the user's timezone. If available add it as the time-zone header to support relative dates.
* Can be overridden by the config

feat: client - automatic time-zone header

---

runtime/apis/authapi/token_endpoint.go
runtime/apis/authapi/token_endpoint_test.go
runtime/oauth/id_token.go

Improving the error response message when in ID token exchange an identity does not exist and createIfNotExists is `false`.

fix: no identity exists error messsage in token exchange

---

tools/generator.go
tools/proto/tools.pb.go
tools/proto/tools.proto
tools/testdata/blog/tools.json

When generating tool configs, we are now generating `related_tools` for DELETE actions as well. These related tools are list actions that operate on the same model, with the intent of providing all the various list options for the model in question.

fix: generate related tools for delete actions

---

packages/functions-runtime/src/File.js

Fix typo which was referencing `this.filename` outside of an object, when storing files in s3 via the custom functions env

fix: fix storage of files on S3

---

go.mod
go.sum

Legacy dependency removed. Vanta requirement.  Also fixed go.sum.

chore: removed legacy go-jose

---

schema/testdata/errors/attribute_computed.keel
schema/testdata/errors/enum_default_no_expression.keel
schema/validation/default_attribute.go

Validation against using `@default` and `@computed` together

fix: default cannot be used on computed fields

---

db/db.go
migrations/migrations.go

Setting the `intervalstyle` output as part of the migrations would not set it for subsequent db connections, as the `intervalstyle` option is a connection configuration which gets reset to the default `postgres` value on later new connections.

fix: set the default intervalstyle for all db connections

---

integration/testdata/computed_fields_one_to_one/schema.keel
integration/testdata/computed_fields_one_to_one/tests.test.ts
integration/testdata/computed_fields_self_referencing/main.test.ts
integration/testdata/computed_fields_self_referencing/schema.keel
migrations/migrations.go
runtime/actions/generate_computed.go

Fixing the bug that Radu found when using a field name referencing a model which has a different name to the model.

fix: bug with computed and one to one

---

migrations/migrations.go
migrations/migrations_test.go
migrations/sql.go
migrations/testdata/computed_field_add_required.txt
migrations/testdata/computed_field_changed_expression.txt
migrations/testdata/computed_field_changed_to_computed.txt
migrations/testdata/computed_field_changed_to_required.txt
migrations/testdata/computed_field_initial.txt
migrations/testdata/computed_field_many_to_one.txt
migrations/testdata/computed_field_many_to_one_changed.txt
migrations/testdata/computed_field_multiple_depend.txt
migrations/testdata/computed_field_renamed_field.txt

Migrations for computed fields and NOT NULL
===
Previously, if a new _required_ computed field was added to a model or an existing field was made into a _required_ computed field, then there would be a NOT NULL constraint error from the database as existing rows would have that column set to NULL before the recomputing could occur.
This fixes the issue by deferring the NOT NULL constraint until after the recomputing is done.

fix: required computed fields and null constraint

---

cmd/database/database.go

I can't explain why this isn't working for one of our customers when using 0.0.0.0, however after some reading it seems 127.0.0.1 should actually be used when connecting from a client.
> When connecting to a PostgreSQL instance running in Docker from the host machine, you should use 127.0.0.1 (localhost) rather than 0.0.0.0. Here's why:
> - 0.0.0.0 is a special IP address that means "all IPv4 addresses on the local machine" when used as a binding address for servers
> - 127.0.0.1 specifically refers to the loopback interface (localhost)
> - When connecting as a client, you want to specify the actual address you're connecting to, not a binding address

fix: using 127.0.0.1 instead of 0.0.0.0

---

packages/wasm/index.test.ts
schema/validation/validation.go

Disabling the Keel studio validation warnings as these are appearing in non-Studio builds in the Console.

fix: disabling keel studio warnings

---

schema/testdata/errors/relationships_update_nested_invalid_input.keel
schema/testdata/errors/set_attribute_built_in_fields.keel
schema/testdata/proto/action_inputs_in_both_query_and_with/proto.json
schema/testdata/proto/action_inputs_in_both_query_and_with/schema.keel
schema/validation/unique_attribute.go
schema/validation/update_nested_inputs.go
schema/validation/validation.go

Improvements to the keel validator:
* Explicitly check update actions to make sure there are no nested fields used as inputs as the runtime currently doesn't support updating related models; e.g.
```erlang
model Post {
fields {
name Text
categ Category
}
actions {
update updatePost(id) with (name, categ.name) <-- this is not allowed
}
}
model Category {
fields {
name Text
posts Post[]
}
}
```

fix: validator improvements

---

config/auth.go
integration/testdata/client_auth/keelconfig.yaml
integration/testdata/client_auth/main.test.ts
node/templates/client/core.ts
runtime/apis/authapi/authorize_endpoint.go
runtime/apis/authapi/providers_endpoint.go
testing/testing.go

In the client SDK, correctly parsing the providers collection under the `data` fields as now required by the `APIResult` wrapper.

fix: get auth providers in client sdk

---

config/auth.go
config/fixtures/test_auth_invalid_issuer.yaml

When marshalling an auth provider to yaml, if the `issuerUrl` is empty (which is valid for slack/google/etc providers) we must omit it from the yaml otherwise it will be written as `issuerUrl: ""` which will cause the validator to fail later on when loading config from bytes as part of a deployment pipeline.

fix: update auth provider struct

---

integration/testdata/simple_database_test/tests.test.ts
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/functions-runtime/src/ModelAPI.test.js
packages/functions-runtime/src/QueryBuilder.js
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml

Upgraded Kysely and deprecated `orWhere` in the ModelAPI
===
Kysely updated to 0.27.5, which included some breaking changes to their API.  This unlocks Kysely's expression builder updates.
We have also deprecated the `orWhere` function on the ModelAPI.

feat: upgraded kysely

---

tools/proto/tools.pb.go
tools/proto/tools.proto

Changing the structure of the Record View Display layout. This moves the stepper configuration in a separate field and adds an enabled field in order to temporarily disable a stepper without losing all information

refactor: change record view config

---

node/codegen.go
node/codegen_test.go

Removed the Model API query builder's `orWhere` TypeScript definition.

fix: removed orwhere ts definitions

---

migrations/indexes.sql
migrations/introspection.go
migrations/migrations.go
migrations/migrations_test.go
migrations/sql.go
migrations/testdata/indexes_added_inputs.txt
migrations/testdata/indexes_changed.txt
migrations/testdata/indexes_removed_inputs.txt

Auto-indexing
===
We now add a standard column index on any field which is used as a query input to an action AND fields which are faceted.
This will also consider nested relationship lookup query inputs.
For example, the schema below will have the following indexes created:
```sql
CREATE INDEX "customer__name__idx" ON "customer" ("name");
CREATE INDEX "order__category__idx" ON "order" ("category");
CREATE INDEX "order__price__idx" ON "order" ("price");
CREATE INDEX "order__quantity__idx" ON "order" ("quantity");
```
```
model Order {
fields {
price Decimal
quantity Number
customer Customer
category Category?
tag Text
}
actions {
list listOrders(customer.id, customer.name, category, tag?) {
@facet(price, quantity, category)
}
}
}
model Customer {
fields {
name Text
}
}
```

feat: auto-indexing on inputs and facet fields

---

schema/testdata/errors/attribute_expression_unresolvable_rhs.keel
schema/testdata/errors/clashing_explicit_implicit_inputs.keel
schema/validation/conflicting_value_inputs.go
schema/validation/validation.go

There is no need to restrict a field which is filtered by inputs and in `@where`.  See example schema below where this case would be valid.  This PR relaxes that condition, but we still validate against using write values and `@set` on the same field.
```
model Order {
fields {
quantity Number
price Decimal
category Text
status Status
}
actions {
list listOrders(status?, category?) {
@where(order.status != Status.Cancelled)
}
}
}
```

fix: conflicting where inputs

---

node/client.go
node/client_test.go

This changes the generated APIClient to not need to include all of the actions on the JavaScript object. The generated actions were all doing exactly the same thing, calling `rawRequest` with its own function name and a single parameter. So this makes the APIClient a Proxy which for any child name returns a function that calls `rawRequest` with that name. And it still generates all the types so the Proxy has the exact same type shape as the APIClient did before.
This reduces bundle size significantly, especially with large API surfaces. Rather than scaling with the number of actions it is now just a constant sized small Proxy object. For example the APIClient in Bravely has 213 actions, and the generated APIClient (after types compiled out) was 41kb (4kb gzipped). Now it's 343 bytes (195 …

fix: generate the client api with proxy that calls into rawrequest to save bundle size

---

packages/functions-runtime/src/File.js

Changing the presigned URL for files to inline content disposition so that clients have the option to display the file contents in the browser rather than forcing a download.
See thread: https://teamkeel.slack.com/archives/C03DJNS3BD0/p1740420868030909

fix: presigned file urls with inline content disposition

---

packages/functions-runtime/src/File.js

Fix for the following functions runtime exception:
```
TypeError: URL.parse is not a function
at Object.endpointProvider (/var/task/node_modules/.pnpm/@teamkeel+functions-runtime@0.404.1_@aws-sdk+client-sso-oidc@3.750.0/node_modules/@teamkeel/functions-runtime/src/File.js:37:18)
at getEndpointFromInstructions (/var/task/node_modules/.pnpm/@smithy+middleware-endpoint@3.2.8/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:139:33)
at <anonymous> (/var/task/node_modules/.pnpm/@smithy+middleware-endpoint@3.2.8/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:186:22)
at <anonymous> (/var/task/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.716.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22)
at <anonymous> …
```

fix: url parsing for files in functions

---

packages/functions-runtime/src/File.js

The S3 client in the functions runtime now sets up the client with the test endpoint only if `TEST_AWS_ENDPOINT` exists.

fix: s3 client in functions

---

.github/workflows/go.yml
.github/workflows/test_npm_modules.yml
compose.yaml
packages/functions-runtime/compose.yaml
packages/functions-runtime/src/ModelAPI.test.js
packages/functions-runtime/src/handleJob.test.js
packages/functions-runtime/src/handleRequest.test.js
runtime/actions/query.go
runtime/actions/query_test.go

Facet queries are not valid for pg15.  This issue is because Postgres [relaxed an aliasing rule from v15 to v16](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=bcedd8f5f).  This fix amends the facet SQL generation to be compatible with pg15.
I've also set our CI and local tests to use pg15.

fix: facet query compatibility with pg15

---

.goreleaser.yaml

Fixes the goreleaser error encountered:
```
error=archive named dist/keel_0.406.1_linux_amd64.tar.gz already exists. Check your archive name template
```

build: goreleaser duplicate names

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml

The following error was being experienced with `keel run`.  This is because the functions-runtime was resolving esbuild as 0.21.5 and testing-runtime as 0.25.0 due to the underlying `vite` dependency being different.  Forcing a `vite` version in both projects should fix this.
```npm ERR! code 1
npm ERR! path /codebuild/output/src44115871/src/node_modules/@teamkeel/testing-runtime/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! /codebuild/output/src44115871/src/node_modules/@teamkeel/testing-runtime/node_modules/esbuild/install.js:135
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Expected "0.25.0" but got "0.21.5"
npm ERR! …
```

fix: esbuild version mismatch

---

cmd/program/commands.go

Improved the watcher to exclude any hidden folders.  Also, hidden folders were not being ignored if the file change was occurring at the root of that hidden folder.  This has been fixed.

fix: watcher ignore list improvements

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/input_get_entry_actions/tools.json

When generating response fields for tools, we're now including a wrapper response field for models that have been embedded.

fix: tools generate wrapping response field for embedded models

---

runtime/actions/pagination.go
runtime/actions/query.go
runtime/actions/query_test.go

Setting `first` to 0 would result in the default of 50 being used.  This change allows for a zero-size page.

fix: allow zero page size on list

---

runtime/actions/get.go

When resolving a `get` action which has no results (i.e. item not found), we should not attempt to retrieve any embedded data

fix: prevent embedding data when no results are available

---

integration/testdata/computed_fields_model_field/schema.keel
integration/testdata/computed_fields_model_field/tests.test.ts
migrations/migrations.go
migrations/migrations_test.go
migrations/sql.go
migrations/testdata/computed_field_model_fields.txt
node/codegen.go
runtime/actions/generate_computed_test.go
schema/testdata/errors/attribute_computed.keel
schema/testdata/errors/attribute_computed_expression.keel
schema/validation/computed_attribute.go

Computed on relationship fields
===
One can now use `@computed`  on to-many relationship fields.  See example below:
```
model OrderJob {
fields {
customer Customer @computed(orderJob.order.customer)
order Order 
}
}
model Order {
fields {
customer Customer
}
}
model Customer {
fields {
name Text
orders Order[]
}
}
```

feat: computed on relationship fields

---

expressions/options/options.go
integration/testdata/computed_fields/schema.keel
integration/testdata/computed_fields/tests.test.ts
integration/testdata/computed_fields_model_field/schema.keel
integration/testdata/computed_fields_model_field/tests.test.ts
migrations/migrations.go
migrations/migrations_test.go
migrations/sql.go
migrations/testdata/computed_field_model_fields.txt
node/codegen.go
runtime/actions/generate_computed.go
runtime/actions/generate_computed_test.go
schema/testdata/errors/attribute_computed.keel
schema/testdata/errors/attribute_computed_expression.keel
schema/validation/computed_attribute.go

Computed fields for text types
===
We now support computing text values for `Text` fields and string concatenation.  For example,
```
model Order {
fields {
title Text @computed(order.customer.name + " order")
customer Customer
}
}
```

feat: computed fields support for text

---

node/bootstrap.go
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml
packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

`keel test` was running into type issues with the vitest expect extensions (`toHaveError`, `toHaveAuthorizationError` and `toHaveAuthenticationError`).  Upgrading to `3.0.8` and **fixing the version number** has resolved the issue.

fix: vitest dep issue with expect extensions

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/config_use_api/tools.json
tools/testdata/one_to_many_links/tools.json

When generating embedded tools for a get tool that operates on a model that has a has many relationship, the embedded tool should not display the field for the source model (i.e. the one for the get tool) as it is redundant.
I.e. a `get-order`, embeds `list-order-lines`, this list tool should have a response override to hide the `order` column for all order lines.

chore: hide source model when generating embedded tools

---

cmd/program/commands.go
go.mod
go.sum

Changes the filesystem watcher from radovskyb/watcher to fsnotify, which uses filesystem events instead of polling. This results in a significant drop in CPU usage. 
Previously while running keel I was seeing 60% cpu usage and 1600 energy usage while idle. This drops it to 0.5% cpu usage and 0.5 energy usage for me.
I am not experienced with Go but this looks like it's correct with the same behavior as before, but please let me know if I missed anything and I can fix it :)

fix: change the filesystem watcher to use fsnotify for less cpu usage

---

migrations/sql.go

"Modification" migrations were being printed out on `keel run` when no change had occured;
```
Schema changes:                                                                                                                                 
- MODIFIED FieldTypeTest.textArray                                                                                                             
- MODIFIED FieldTypeTest.numberArray                                                                                                           
- MODIFIED FieldTypeTest.decimalArray                                                                                                          
- MODIFIED FieldTypeTest.booleanArray …
```

fix: unnecessary array migrations

---

node/bootstrap.go

Bumps kysely to the latest version; this is consistent to the requirements of the `functions-runtime` package.

chore: bump kysely to 0.27.6

---

auditing/auditing.go
events/events.go
integration/testdata/events_basic/functions/updateTrackers.ts
integration/testdata/events_basic/schema.keel
integration/testdata/events_basic/subscribers/verifyUpdate.ts
integration/testdata/events_basic/tests.test.ts

When performing updates on a large set of data for a model which has an event subscriber, there was a performance issue in how we looked up the "previousData" in the event payload.  For each changed row, there was a lookup.  This has been changed to perform a single lookup for multiple changes.

perf: previous data lookup in events

---

cmd/program/model.go
deploy/lambdas/runtime/cmd/main.go
deploy/lambdas/runtime/flows.go
deploy/lambdas/runtime/handler.go
deploy/program.go
integration/testdata/flows/tests.test.ts
runtime/flows/events.go
runtime/flows/orchestrator.go
runtime/runtime.go
testing/aws.go
testing/testing.go

Refactors the flow orchestrator to handle events and trigger new orchestrations by pushing events for itself. In the case of the orchestrator being initialised without a SQS client & queue URL, the events will be handled synchroneously instead of being pushed onto a queue.
Keel deploy will now provision a new queue for flows, and a new runtime lambda in flow mode, which is invoked via queue events.

feat: flow orchestration via SQS

---

migrations/flows.sql
node/codegen.go
node/codegen_test.go
packages/functions-runtime/src/StepRunner.js
packages/functions-runtime/src/handleFlow.js
packages/functions-runtime/src/routes/customResponse.ts
runtime/flows/flow.go
runtime/flows/orchestrator.go

Steps can now be configured with a max retry limit and a timeout as shown in the example below.
If not provided, max retries is 5 and the timeout is 10 minutes.
```ts
export default MyFlow(async (ctx, inputs) => {
const thing = await ctx.step("insert thing", async () => {
return await models.thing.create({
name: inputs.name,
});
},
{
maxRetries: 3,
timeoutInMs: 500,
}
);
});
```
Note that the API design still needs to be addressed.

feat: step retry limit and timeouts

---

runtime/apis/flowsapi/flow_handler.go
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Introduces a new workflow API endpoint:
* `PUT flows/json/[flowName]/[runID]/[stepID]`
This sets the given user input as the value of the given `PENDING` `UI` step. It marks the step as `COMPLETED` and then triggers the orchestrator to continue running the flow.

feat: set UI step value endpoint

---

node/bootstrap.go
node/codegen.go
node/codegen_test.go

Certain types used in the SDK were not referencing the functions-runtime module correctly.  Due to `skipLibCheck: true` this has not failed TS type checking steps.  
This PR fixes the unresolved types.

fix: unresolved sdk types

---

runtime/apis/flowsapi/flow_handler.go
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Adds the ability to cancel a running/new flow run:
```
POST flows/json/[flowName]/[runID]/cancel
```

feat: cancel a running/new flow run

---

runtime/apis/flowsapi/flow_handler.go
runtime/flows/flow.go
runtime/flows/run.go

Handles a new endpoint: 
```
GET flows/json/[flowName]
```
The endpoint supports cursor pagination through query fields:
* `limit` = number of items to return
* `after` & `before` = run ids

feat: add endpoint to list flow runs

---

runtime/apis/flowsapi/list_flows_endpoint.go
runtime/openapi/openapi.go
runtime/openapi/openapi_test.go
runtime/openapi/testdata/flow.json
runtime/openapi/testdata/flow.keel
runtime/runtime.go

Adds a new endpoint: `GET /flows/json/openapi.json` 
Generates a openapi schema with the input messages used to start each flow.
Refactored the openapi test to assert either job schemas, flow schemas or general API schemas

feat: add openapi.json endpoint to the flows API

---

runtime/flows/flow.go

Previously the cursor pagination was implemented with before & after being.. time based; i.e. retrieve items that happened before the cursor. This PR changes this behaviour to enforce a consistent ordering (newest flows at the top) and `before` & `after` take in consideration the position of the items rather than the time they happened: e.g.
* retrieve 5 items after x will return the 5 flows that would be displayed after x in a list where the newest flows are at the top; i.e. the 5 flows that took place before x

fix: amend cursor pagination for flows

---

migrations/flows.sql
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/handleFlow.js

Adds a `span_id` column to steps and populates it with the OTEL span id

fix: store spanId when completing a flow step

---

.github/workflows/release.yml

Builds the typescript in the functions-runtime package during the NPM publish job during the release.

build: build functions runtime on release

---

node/codegen.go
runtime/flows/flow.go
runtime/flows/run.go

Return stages config as part of the get flow run response. 
This stage config will be set with the flow config returned from the functions runtime when retrieving ui components of a pending UI step.
Also, this PR exports the FlowConfig runtime type as part of the generated sdk

fix: return flow config when returning ui components

---

node/bootstrap.go
node/codegen.go

Use `vite-tsconfig-paths` to support additional user configured paths via TS config

feat: support custom TS paths in testing

---

integration/testdata/flows/flows/myFlow.ts
migrations/flows.sql
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/elements/display/table.ts
packages/functions-runtime/src/flows/ui/elements/select/single.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/flows/ui/page.ts
packages/functions-runtime/src/handleFlow.js
packages/functions-runtime/src/index.ts

New argument on the page function for the unique name of the step:
```ts
const values = await ctx.ui.page("Update page", {
title: "Update thing",
stage: "Updating",
description: "Overwrite the existing data in thing",
// ..
});
```
Function steps now have a configuration argument, which includes `stage`.  Timeout and retry configuration also moved here.
```ts
const thing = await ctx.step("insert thing",
{ stage: "Updating" },
async () => {
// ..
}
);
```
Step stages now persisted:

fix: page name, step config, stage persistence

---

tools/config.go

When configuring links and amending data mappings, we were failing to apply the user added data mapping. This is now fixed.

fix: fix datamapping configs on tool links

---

node/bootstrap.go

Pretty sure this is just because on Windows a newline is "\r\n"... `TrimSpace` should handle this.
```
PS C:\Users\source\repos\KeelDemos\inventory_management_mm> keel validate
✨ Everything's looking good!
PS C:\Users\source\repos\KeelDemos\inventory_management_mm> keel run     
Running Keel app in directory: C:\Users\source\repos\KeelDemos\inventory_management_mm
Press q to quit
❌ There is an issue with your dependencies:
Malformed version: 22.15.0
```

fix: use TrimSpace to support Windows

---

schema/testdata/proto/computed_fields/proto.json
schema/testdata/proto/computed_fields/schema.keel
schema/validation/rules/actions/input_type.go

This change allows the use of computed fields as query inputs for actions (i.e. `list`)

fix: allow querying by computed fields

---

expressions/options/options.go
integration/testdata/computed_fields/schema.keel
integration/testdata/computed_fields/tests.test.ts
migrations/sql.go
schema/validation/computed_attribute.go

Support for negation of timestamps in computed expressions on `Duration` field types.   For example:
```
model Order {
fields {
orderDate Timestamp 
deliveryDate Timestamp?
leadTime Duration? @computed(computedDuration.deliveryDate - computedDuration.orderDate)
}
}
```

fix: negation of timestamp types to produce a duration

---

integration/testdata/flows/schema.keel
packages/functions-runtime/src/flows/index.ts

This change overloads the step function definition so that is it possible to omit the options argument.  i.e. these are both valid:
With options:
```
await ctx.step(
"my step", 
{ stage: "stage 1" }, 
async() => {
...
}
);
```
Without options:
```
await ctx.step(
"my step", 
async() => {
...
}
);
```

fix: flow step overload

---

runtime/flows/flow.go

When retrieving flow runs, by default steps should be ordered based on their `created_at` timestamp

fix: order steps when retrieving flow runs

---

migrations/flows.sql
packages/functions-runtime/src/flows/disrupts.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/handleFlow.js
runtime/flows/orchestrator.go

`error` column
--
If an error occurs on a step, this will be stored in the new `error` column.
Timeouts and retries handling
--
These columns have been removed from the database, and now the functions runtime handles them.

fix: flow step errors, timeouts and retry handling

---

integration/testdata/flows/tests.test.ts
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Adds a new flow run status: `AWAITING_INPUT`. Whenever a flow run is orchestrated and it is pending a UI step, the status will be set to awaiting input. Once a flow is orchestrated again, with data when in an `AWAITING_INPUT` status, the status will be updated to `RUNNING` and the flow runtime invoked. 
This will allow FE to differentiate between flow runs that are currently in progress (executing) and the ones that are awaiting user input.

chore: add a AWAITING_INPUT run status

---

integration/testdata/flows/flows/mixedStepTypes.ts
integration/testdata/flows/tests.test.ts

Mostly just making the assertions on the API responses more robust. It does make the tests more verbose but for now I think we will benefit from knowing exactly what is being returned.

test: more tests for flows

---

integration/testdata/flows/flows/scalarStep.ts
integration/testdata/flows/schema.keel
integration/testdata/flows/tests.test.ts
runtime/apis/flowsapi/flow_handler.go
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Support scalar types being returned from steps.  E.g.
```ts
export default ScalarStep({}, async (ctx) => {
await ctx.step("scalar step", async () => {
return 10;
});
});
```

fix: step support for scalar return values

---

integration/testdata/flows/flows/onlyPages.ts
integration/testdata/flows/schema.keel
integration/testdata/flows/tests.test.ts
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Whenever we invoke the functions runtime to execute a flow, we receive some UI components data: Flow config, and page UI components to be displayed for the currently pending UI step. 
This PR refactors the internal orchestration to return these components when applicable. These components then are injected onto the current flow run struct as part of the WAPi responses.
Now we will have the flow config and any page UI components as part of the response of the startFlow WAPI endpoint (Note: page UI components data will be available only if the first step is a UI step)

refactor: retrieval of flow ui components through orchestration

---

packages/functions-runtime/package.json

We need to include the `scripts` path when publishing to NPM as we now have scripts which we run on post install

fix: missing scripts in functions runtime

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml

Moving some devDependencies to dependencies in the functions-runtime `package.json`.  This is because they are required during `postinstall`.

fix: postinstall to postbuild for functions runtime scripts

---

migrations/columns.sql
migrations/flows.sql
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/handleFlow.js
runtime/flows/flow.go

Moved the flows database tables to the new `keel` database schema.  Note that these tables are now not visible in the Console's database viewer.

fix: moved flows tables to keel db schema

---

packages/functions-runtime/src/flows/index.ts

Because steps functions serialise the returned values to JSON, we need to ensure that the return type can be safely deserialised from JSON back into the original type.  We do this by adding the following generic constraint.

fix: json serializable type constraint on step return type

---

integration/testdata/flows/flows/errorInFlow.ts
integration/testdata/flows/schema.keel
integration/testdata/flows/tests.test.ts
packages/functions-runtime/src/handleFlow.js

An error thrown in the body of a flow (i.e. not in a step function) will cause the entire flow to fail.  I dont think we need to have a `error` column for this as it's appropriate the the error is just captured on the trace span.
Also reworked error handling in `handleFlow` such that an error thrown in the flow function is handled separately to an error thrown in our functions-runtime code.

fix: handling error thrown in flow body

---

integration/testdata/built_in_actions/main.test.ts
runtime/actions/query.go
runtime/actions/query_test.go

Text filters for list actions are currently case sensitive. This makes them case insensitive

feat: make text input filters case insensitive

---

tools/config.go
tools/diff.go

Tool config to persist the page size in list cursor pagination.

fix: list page size in tools config

---

go.mod
integration/testdata/flows/tests.test.ts
migrations/flows.sql
runtime/apis/flowsapi/my_runs_endpoint.go
runtime/common/common.go
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go
runtime/openapi/openapi.go
runtime/openapi/testdata/flow.json
runtime/runtime.go

This PR introduces a `started_by` field on flow runs. This holds the identity of the user that started the flow, if applicable.
Alongside this, we are introducing a new endpoint to list the current user's flow runs:
``` GET /flows/json/myRuns?limit=10&status=AWAITING_INPUT,COMPLETED```
or 
``` GET /flows/json/myRuns?limit=10&status=COMPLETED&status=AWAITING_INPUT```
This endpoint accepts pagination parameters: `limit`, `after` and `before`, together with an optional `status` parameter which is used to filter the runs based on their current status. The `status` parameter is a string containing a comma separated list of statuses, or a single status, passed as a query param multiple times e.g. `?status=COMPLETED&status=AWAITING_INPUT`

fix: my flow runs endpoint

---

deploy/lambdas/functions/main.js.go.tmpl
integration/testdata/flows/flows/envStep.ts
integration/testdata/flows/keelconfig.yaml
integration/testdata/flows/schema.keel
integration/testdata/flows/tests.test.ts
node/codegen.go
node/codegen_test.go
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/handleFlow.ts

Adding the schema defined secrets & env vars to the flows context:
Given a keel config:
```
environment:
- name: PERSON_NAME
value: "Pedro"
- name: MY_ENV_VAR
value: "my env value"
secrets:
- name: MY_SECRET
```
The env vars and secrets will now be available in the flow
```
import { MyFlow } from "@teamkeel/sdk";
export default MyFlow({}, async (ctx) => {
await ctx.step("env step", async () => {
console.log(ctx.secrets.MY_SECRET);
console.log(ctx.env.MY_ENV_VAR);
return ctx.env.PERSON_NAME;
});
});
```
This feature requires a lambda handler change to instantiate the flow handler with the new context values

feat: add env and secrets to flow context

---

integration/testdata/functions_custom/functions/noInputs.ts
integration/testdata/functions_hooks/functions/createBookNoInputs.ts
integration/testdata/functions_hooks/functions/deleteBookNoInputs.ts
integration/testdata/functions_hooks/functions/getBookNoInputs.ts
integration/testdata/functions_hooks/functions/updateBookNoInputs.ts
integration/testdata/functions_hooks/main.test.ts
node/codegen.go
node/codegen_test.go
node/templates/functions/create.js
node/templates/functions/delete.js
node/templates/functions/get.js
node/templates/functions/types.d.ts
node/templates/functions/update.js

When no inputs are defined for actions and flows, then keen the `inputs` argument in the function definitions and make it of type `never`.

fix: type never for empty inputs in functions

---

migrations/migrations.go
migrations/sql.go
migrations/testdata/sequence_field_unchanged.txt

Fixes a bug which was causing the migrations for sequesnce fields to be added at all times.
Sequence fields have a default value, even though the default value in the proto schema is undefined.

fix: fix sequences migration bug

---

tools/config.go
tools/diff.go
tools/generator.go

Fixing a few edge cases of tools configurations:
* having multiple tools contenders for a get entry action; we will now always choose the first one from an alphabetically sorted list
* when changing the target tool for a link, the configuration diffing will now treat the link as a new one, in order to prevent passing through data mappings from generated links pointing to other tools

fix: tool links configurations to treat changed targets as new links

---

integration/testdata/flows/tests.test.ts
runtime/apis/flowsapi/list_flows_endpoint.go

Changing the return format of the stats endpoint from `{stats: [...]}` to `{[...]}`

fix: change stats return format

---

integration/testdata/flows/flows/validationPage.ts
integration/testdata/flows/schema.keel
integration/testdata/flows/tests.test.ts
integration/testdata/flows_errors/flows/errorInValidation.ts
integration/testdata/flows_errors/schema.keel
integration/testdata/flows_errors/tests.test.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/flows/ui/page.ts
runtime/flows/orchestrator.go

Validation for pages.  I've also changed the validation functions so that you can also return `undefined` which means you can leave out the return statements entirely which feels good to me.  See example:
```ts
await ctx.ui.page("first page", {
content: [
ctx.ui.inputs.text("email", {
label: "Email",
optional: true,
validate(value) {
if (!emailRegex.test(value)) {
return "Not a valid email";
}
},
}),
ctx.ui.inputs.text("phone", {
label: "Phone",
optional: true,
validate(value) {
if (!phoneRegex.test(value)) {
return "Not a valid phone number";
}
},
}),
],
validate: async (data) => {
if (!data.email && !data.phone) {
return "Email or phone is required";
}
},
});
```

fix: flows page validation

---

deploy/build.go
packages/functions-runtime/src/handleFlow.test.js
packages/functions-runtime/src/handleFlow.ts
packages/functions-runtime/src/handleJob.js
packages/functions-runtime/src/handleJob.test.js
packages/functions-runtime/src/handleRequest.js
packages/functions-runtime/src/handleRequest.test.js
packages/functions-runtime/src/handleRoute.js
packages/functions-runtime/src/handleRoute.test.js
packages/functions-runtime/src/handleSubscriber.js
packages/functions-runtime/src/handleSubscriber.test.js
runtime/flows/orchestrator.go

Previously the CLI would bomb when a function file was missing.  Or if the file exists, but is empty, then we'd see `Cannot read properties of undefined (reading 'fn')` in the traces.
This PR fixes these two issues by gracefully handling missing files or functions.  The CLI won't bomb out and the following will be recorded in the span:

fix: gracefully handle missing ts files or functions

---

node/codegen.go

If we don't explicitly import each of the function runtime types in the code generated SDK, then we don't risk a TypeError when the runtime is a version ahead of the NPM packages (which is not unlikely at the moment with our current setup)

fix: decouple func runtime types

---

cmd/program/model.go
runtime/flows/event_sender.go
runtime/flows/orchestrator.go

Updates the flows orchestrator to receive a EventSender instead of a sqs queue & sqs client.
Introduces a SQSEventSender & a NoQueueEventSender (instead of sending the message to the orchestrator via the queue, it invokes the orchestrator's event handler in a new goroutine).

fix: abstract the sqs event sender from the orchestrator

---

tools/generator.go
tools/testdata/composition/fields/expected/create-product.json
tools/testdata/generate_testdata.go
tools/testdata/generator/input_get_entry_actions/tools.json

When generating lookup action links for inputs, we should only generate them for fields that reference a model ID.

fix: generate lookup actions only for model ID fields

---

runtime/flows/flow.go

Whilst the ksuids are derived from time of generation and can in theory be used for ordering, the way string comparison works as part of the query produces undesired results, especially when there are many items generated in quick succession. Thus, ordering flow runs must happen by `created_at` instead of the `id`; with the ID being used only as a cursor.

fix: list flows ordering

---

runtime/openapi/openapi.go
runtime/openapi/testdata/flow.json

Adds `startTime` to the runs responses as part of the flow api's OpenAPI schema

fix: add startTime to flow runs openapi schema

---

functions/functions.go
runtime/flows/orchestrator.go

Introduces a struct that contains all flow invocation args. This will make it easier to add future optional data without having to refactor other functions (i.e. `orchestrator.CallFlow`)

refactor: change flow calling args

---

functions/functions.go
runtime/apis/flowsapi/flow_handler.go
runtime/flows/flow.go
runtime/flows/orchestrator.go
runtime/flows/run.go

Adds a new handler to the flows API for callbacks:
```
POST flows/json/[flowName]/[runID]/[stepID]/callback?name={callbackName}}&element={elementName}
```
This will invoke the functions runtime synchronously in order to perform the requested callback and proxy back the response.

chore: add runtime flow's API handler for callbacks

---

schema/makeproto.go
schema/testdata/proto/operations_inputs/proto.json
schema/testdata/proto/operations_inputs/schema.keel

A list action should handle `Markdown` fields used as filters in the same way as `Text` fields

fix: handle filtering by markdown fields on list actions

---

integration/testdata/tasks/schema.keel
integration/testdata/tasks/tests.test.ts
runtime/apis/tasksapi/handler.go
runtime/tasks/tasks.go

This performs basic task assignment when calling upon the `POST topics/{name}/tasks/next` endpoint.  The next available task will be assigned to the currently authenticated user.  The following basic rules apply:
- If the user already has a task assigned to them, then return that task instead
- The candidate task is the next NEW and unassigned task whose deferred date has passed (if even set)
Still to do is to apply task ordering by the `@order` attribute.  Also need to write a lot more tests.

chore: basic task assignment

---

packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/elements/interactive/bulkScan.test-d.ts
packages/functions-runtime/src/flows/ui/elements/interactive/bulkScan.ts
packages/functions-runtime/src/flows/ui/elements/interactive/pickList.test-d.ts
packages/functions-runtime/src/flows/ui/index.ts
runtime/openapi/testdata/flow.json
runtime/openapi/uiConfig.json

* Element to support bulk barcode capture
* Supports 3 strategies to handle duplicates
* Treat each scan as a separate entry (default behaviour) 
*  Reject duplicates
* Track quality of each unique code

feat: bulkScan element

---

functions/functions.go
integration/testdata/flows_elements/flows/callbackFlow.ts
integration/testdata/flows_elements/schema.keel
integration/testdata/flows_elements/tests.test.ts
packages/functions-runtime/src/flows/disrupts.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/testingUtils.ts
packages/functions-runtime/src/flows/ui/elements/input/boolean.ts
packages/functions-runtime/src/flows/ui/elements/input/number.ts
packages/functions-runtime/src/flows/ui/elements/input/text.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/flows/ui/page.ts
packages/functions-runtime/src/handleFlow.ts
packages/testing-runtime/src/FlowExecutor.mjs
packages/testing-runtime/src/index.d.ts
runtime/apis/flowsapi/flow_handler.go
runtime/flows/orchestrator.go
runtime/flows/run.go
runtime/openapi/flowsapi.go
runtime/openapi/testdata/flow.json

This PR adds flow UI element callbacks.
Basic inputs now have a `onLeave` callback which can be defined as follows:
```ts
ctx.ui.inputs.number("orderCount", {
label: "How many orders should I create?",
defaultValue: 1,
onLeave: (data:number) => {
return data * 2
}
})
```
As these elements are defined on a flow page: `await ctx.ui.page("pageName", ...}` whilst the flow run is Pending input for that particular page, a callback can be perfromed from the frontend to the execute the user defined function. this is done via a new endpoint in the Flows API:
```
// POST flows/json/[flowName]/[runID]/[stepID]/callback?callback={callback}&element={elementName}
```
in our example, `callback=onLeave` and `element=orderCount`.
Support for callbacks is added to the testing package as well, e.g.:
```ts …
```

feat: UI elements callbacks

---

rpc/rpcApi/server.go

Filters out requests to the flows api from the monitoring page when running a local project.

fix: filter out flows api traces from local monitoring

---

packages/testing-runtime/src/FlowExecutor.mjs

Missing import for the jwt module in the flows test executor.

fix: jwt import in flow test executor

---

integration/testdata/flows/tests.test.ts
runtime/flows/flow.go

When cancelling steps, set the endTime for the cancelled step to be the current timestamp

fix: set end time when cancelling steps
