teamkeel/keel

schema/validation/unused_inputs.go

Fixed issue experienced by Jay, whereby labelled inputs were not being permitted on function actions.

fix: labelled inputs sometimes validated against for functions

---

config/auth.go
config/config_test.go
runtime/apis/authapi/authorize_endpoint.go
runtime/apis/authapi/authorize_endpoint_test.go
runtime/apis/authapi/revoke_endpoint_test.go
runtime/apis/authapi/token_endpoint_test.go
runtime/oauth/id_token_test.go
runtime/oauth/oauthtest/oidc_test_server.go

Client secrets now stored properly as Keel secrets.

fix: auth client secrets as keel secrets

---

cmd/init.go

We weren't handling the `ErrInterrupt` error from promptui in our panic handler, so the whole stack trace was being dumped.
Now handled better...

fix: handling of ctrl+c aborting during init command

---

node/bootstrap.go
packages/client-react-query/package.json
packages/client-react-query/pnpm-lock.yaml
packages/client-react/package.json
packages/client-react/pnpm-lock.yaml
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml
packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

- Updated dependencies for our node packages
- Fixes:
- https://github.com/teamkeel/keel/security/dependabot/16
- https://github.com/teamkeel/keel/security/dependabot/11
- https://github.com/teamkeel/keel/security/dependabot/17

build: updated node package dependencies

---

integration/testdata/functions_custom/schema.keel
integration/testdata/functions_http/schema.keel
runtime/actions/authorization.go
runtime/actions/authorization_test.go

Fixes issue which failed permissions if no `@permission` attribute was defined for some function.

fix: permissions for functions

---

node/client.go
node/client_test.go
proto/query.go

Tests which cover most of the Keel Client code generation.

chore: keel client code generation tests

---

packages/functions-runtime/src/tracing.js
packages/functions-runtime/src/tracing.test.js

Patching `console.error()` and tracing it as a span error. 
The root span will also correctly reflect that an error has occurred:
```console.error("Whoopsie!");```
```console.error(new Error("Whoopsie"));```
```
console.error({
name: "Whoopsie",
reason: "Just because!"
});
```

feat: tracing console error

---

.github/workflows/semantic_release.yml
package-lock.json
package.json

Fixing semantic release action

fix: semantic release action

---

node/codegen.go
packages/functions-runtime/src/ModelAPI.js

- Handling unhandled promise rejections
- Ensuring hasMany ModelAPI inserts are awaited

fix: handling unhandled promise rejections

---

.golangci.yml
migrations/introspection.go
migrations/migrations.go
migrations/sql.go
node/codegen.go
node/codegen_test.go
runtime/actions/expression.go
runtime/actions/filters.go
runtime/actions/list.go
runtime/actions/query_test.go
runtime/actions/scope.go
runtime/apis/graphql/graphql.go
runtime/oauth/access_token.go
schema/backlinks.go
schema/completions/completions.go
schema/expressions/expressions.go
schema/expressions/scope.go
schema/makeproto.go
schema/validation/rules/actions/create_required.go
schema/validation/rules/actions/input_label.go
schema/validation/rules/actions/input_type.go

Reenbled `unparam` lint check and refactored code by removing unused function arguments.

chore: reenabled unparam and removed unused func args

---

node/bootstrap.go
node/bootstrap_test.go

Updating the `tsx` version used

Update tsx dependency

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/functions-runtime/src/database.js

- chore: removing client side pg pooling for functions (#1501)
- chore: using neon dialect for kysely

neon dialect

---

.github/workflows/release.yml
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/functions-runtime/src/database.js

Using the standard PostgreSQL dialect is introducing a 30ms latency to every database request, which is significant.  This [Neon Kysely dialect](https://github.com/seveibar/kysely-neon) does fix that.  This is still in testing.

fix: neon kysely dialect

---

cmd/validate.go

Using `keel validate -json` will now return the following when no errors occurred.  Previous it was returning `✨ Everything's looking good!` which is obviously not JSON.
```json
{
"validationErrors": {
"errors":[],
"warnings":[]
},
"configErrors":{
"errors":[]
}
}
```

fix: keel validation json format for no errors

---

packages/functions-runtime/src/tracing.test.js
runtime/actions/file_uploads.go
storage/database_storer.go

Fix bug that was preventing updates on InlineFiles to be set as null.

fix: handle null InlineFiles updates

---

integration/testdata/jobs_basic/jobs/allInputTypes.ts
node/client.go
node/codegen.go
packages/functions-runtime/src/InlineFile.js

Support for InlineFile.read() from S3

feat: inline files read

---

node/templates/client/core.ts
storage/database_storer.go

Fixes the following type issues on the generated client:

fix: typing in generated client

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/functions-runtime/src/File.js

Fixing an issue where hosted environments are still storing files in `keel_storage`.  Also upgrade s3 client for the functions environment.

fix: file storage persist and upgraded s3 client

---

integration/testdata/schemas_folder/main.test.ts
integration/testdata/schemas_folder/schemas/schema.keel
schema/reader/reader.go

* Look for schemas in a `schemas` directory if it exists as well as the root

feat: support schemas directory

---

packages/functions-runtime/src/File.js

- Set presigned URL to expire in 1 hour.
- Fixed runtime bug with getPresignedUrl()

fix: functions presigned url fixes

---

packages/functions-runtime/src/database.js

This reverts commit 0b342ec15c9bbfb2d14266035019221a9c910f9d.

fix: revert functions database connection limit

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/config_use_api/tools.json
tools/testdata/one_to_many_links/tools.json

The title of tool groups will now be sentence cased

chore: sentence case tool groups

---

packages/functions-runtime/src/database.js

fix: setting neon types correction

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml

Loc AWS sdk versions to minor versions, accepting only new patch versions.

fix: update aws libs versions

---

go.mod
go.sum
packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

- Updating wasm packages and fixing lock file
- Updating go-jose

fix: wasm and go-jose package updagtes

---

go.mod
go.sum
runtime/apis/authapi/authorize_endpoint.go
runtime/oauth/id_token.go

chore: updating oidc package

---

.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/test_npm_modules.yml

Updating to latest node in our pipelines.

chore: updating to latest node in pipelines

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/config_use_api/tools.json
tools/testdata/entry_activity_actions/tools.json
tools/testdata/input_get_entry_actions/tools.json
tools/testdata/input_get_entry_actions_with_relationships/tools.json
tools/testdata/input_lookup_actions_with_relationships/tools.json
tools/testdata/one_to_many_links/tools.json
tools/testdata/with_api_definition_no_config/tools.json

Adds a default Record display layout to all get tools

chore: get tools should have a record display layout by default

---

packages/functions-runtime/src/File.js

I've pulled this change out from #1678 as I've run into an issue where trying to make changes to both JS packages and then relying on those changes in integration tests doesn't always work.
The issue is that although when we install functions-runtime and testing-runtime packages into the test directories we reference the local packages, the testing-runtime package references the [published](https://github.com/teamkeel/keel/blob/main/packages/testing-runtime/package.json#L21) version of functions-runtime in it's package.json, which doesn't have the local changes.
There is probably a better way to solve this (maybe with workspaces) but for now I think the easiest thing is to merge and publish this change and then I can just update the version in #1678.

feat: allow setting a custom endpoint for S3 client

---

integration/testdata/functions_errors/main.test.ts
node/bootstrap.go
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml
testing/testing.go

Upgraded the vitest dependency from 0.34.x to the latest 3.0.7.

fix: upgraded vitest to latest

---

node/bootstrap.go

Updating package versions generated in a client's project package.json.

fix: updated node and ts packages

---

packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

Updating the vitest dependency on the wasm package to the latest.

chore: wasm vitest package update

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/input_get_entry_actions/tools.json

This reverts commit 891b66e3a7161c329591c91cbb061602647fb530. as Console changes are required before releasing this update

fix: revert embedded wrapper field

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml

Bumping  node packages versions

chore: update node packages

---

rpc/rpcApi/server.go
tools/service.go

Allows instantiating the tools service with given user config and in-memory storage

fix: allow using the tools service with in-memory storage

---

cmd/program/commands.go

Fixed watcher to track all new folders creating during `keel run`

fix: watcher to track all new folders

---

schema/format/format.go
schema/format/testdata/route_functions.txt
schema/makeproto.go
schema/parser/parser.go
schema/testdata/errors/route_functions.keel
schema/testdata/proto/route_functions/schema.keel
schema/validation/route_functions.go

What it says on the tin. See tests for more info.

build: update formatter for route functions and more validation

---

node/scaffold.go

Plus a small refactor of this function to tidy it up a bit.

feat: add support for scaffolding out missing route function handlers

---

schema/format/format.go
schema/format/testdata/casing.txt

fix: relaxed enum test case

---

tools/config.go

When configuring embedded tools, we must handle invalid configurations gracefully by not applying them. Future validation will flag these configs but we must not panic when attempting to apply the user config

chore: improve resilience with invalid embedded tool groups

---

tools/generator.go
tools/testdata/blog/tools.json
tools/testdata/entry_activity_actions/tools.json
tools/testdata/with_api_definition_no_config/tools.json

Changing the order of generated entry activity actions by pushing Deletes to the end of the list

chore: update order of generated entry activity actions

---

cmd/localTraceExporter/client.go

It's not enough to just use a lock for writing to a global map, you also need to wrap reads.

fix: ensure all access to global maps happen within a lock

---

node/bootstrap.go
packages/client-react-query/package.json
packages/client-react-query/pnpm-lock.yaml
packages/client-react/package.json
packages/client-react/pnpm-lock.yaml
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml
packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

Updating minor and patch node dependencies where possible in our packages.

chore: updating node deps in packages

---

packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml

Updating neon serverless driver to 1.0.0 (GA)

chore: neon serverless package updated to v1

---

cmd/localTraceExporter/client.go

* Arguments to `maps.Copy` were the wrong way round 🤦 
* I missed that `updateTraceSummary` is only called internally by a function which has already acquired a lock. Refactored this to do that work inline in `UploadTraces` to avoid this issue.

fix: incorrect usage of maps.Copy and attempt to acquire lock twice

---

runtime/flows/orchestrator.go

When handling flow events, the sqs handler will set the spanContext from the event's traceparent:
```
func handler(ctx context.Context, sqsEvent events.SQSEvent) error {
...
var wrapper flows.EventWrapper
err := json.Unmarshal([]byte(message.Body), &wrapper)
if err != nil {
return err
}
// Use the span context from the event payload, which
// originates from the runtime execution that triggered the event.
spanContext := util.ParseTraceparent(wrapper.Traceparent)
if spanContext.IsValid() {
ctx = trace.ContextWithSpanContext(ctx, spanContext)
}
ctx, span := tracer.Start(ctx, "Process event")
defer span.End()
```
... then, any subsequent events emitted by the orchestrator need to pull through the traceparent from the current context. This is what this PR is doing by setting the traceparent …

chore: pass current traceparent to emitted events

---

schema/attributes/computed.go
schema/attributes/permission.go
schema/attributes/where.go

Noticed this test failure - https://github.com/teamkeel/keel/actions/runs/14408615443/job/40556298806?pr=1815
This should fix the issue.

fix: add lock around shared map usage

---

node/scaffold.go

Scaffolds the flow function when running `keel generate`. Files are created in the `flows/` folder:
```
import { NewFlow } from '@teamkeel/sdk';
// To learn more about flows, visit https://docs.keel.so/flows
export default NewFlow(async (ctx, inputs) => {
});
```

feat: scaffold flows functions

---

.github/workflows/lint_javascript.yml
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/elements/display/banner.ts
packages/functions-runtime/src/flows/ui/elements/display/code.ts
packages/functions-runtime/src/flows/ui/elements/display/divider.ts
packages/functions-runtime/src/flows/ui/elements/display/grid.ts
packages/functions-runtime/src/flows/ui/elements/display/header.ts
packages/functions-runtime/src/flows/ui/elements/display/image.ts
packages/functions-runtime/src/flows/ui/elements/display/list.ts
packages/functions-runtime/src/flows/ui/elements/display/markdown.ts
packages/functions-runtime/src/flows/ui/elements/display/table.ts
packages/functions-runtime/src/flows/ui/elements/input/boolean.ts
packages/functions-runtime/src/flows/ui/elements/input/number.ts
packages/functions-runtime/src/flows/ui/elements/input/text.ts
packages/functions-runtime/src/flows/ui/elements/select/single.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/index.ts

First pass of display elements with rich typings
* Divider
* Header
* Markdown
* Table
* List
* Grid
* Code
* Banner
* Image

feat: display elements

---

Makefile
integration/testdata/flows/flows/myFlow.ts
packages/client-react-query/src/index.ts
packages/client-react/src/index.tsx
packages/functions-runtime/src/flows/disrupts.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/elements/display/table.ts
packages/functions-runtime/src/flows/ui/elements/select/single.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/flows/ui/page.ts
packages/wasm/lib/wasm_exec.js

Forcing `make prettier` to use prettier v3.x.x and prettier fixes

fix: prettier fixed version

---

integration/testdata/computed_fields/schema.keel
integration/testdata/computed_fields/tests.test.ts
migrations/migrations.go
proto/schema.go
runtime/actions/generate_computed.go
runtime/actions/generate_computed_test.go

Fixing the use of enum literal values in computed field expressions.

fix: enum literal values in computed expressions

---

schema/makeproto.go
schema/testdata/proto/flow_fields/proto.json
schema/testdata/proto/flow_fields/schema.keel
schema/testdata/proto/flow_permissions/proto.json

Fixed panic caused when using a model as a flow input

fix: model type in flow inputs

---

packages/functions-runtime/src/flows/index.test-d.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/testingUtils.ts
packages/functions-runtime/src/flows/ui/elements/display/grid.test-d.ts
packages/functions-runtime/src/flows/ui/elements/display/grid.test.ts
packages/functions-runtime/src/flows/ui/elements/display/grid.ts
packages/functions-runtime/src/flows/ui/elements/display/list.ts
packages/functions-runtime/src/flows/ui/elements/input/text.ts
packages/functions-runtime/src/flows/ui/elements/select/one.test-d.ts
packages/functions-runtime/src/flows/ui/elements/select/one.ts
packages/functions-runtime/src/flows/ui/index.ts
packages/functions-runtime/src/flows/ui/page.test-d.ts
packages/functions-runtime/src/flows/ui/page.ts

* Creates `_testFlow` and `_testFlowContext` in `testingUtils.ts` to enable easy testing
* Adds some test for elements. 
* `[element].test.ts` for behaviour tests
* `[element].test-d.ts` for type tests

chore: element testing

---

node/development_server.go

Using `filepath.Join` to ensure compatibility with Windows.

fix: functions runtime in windows

---

integration/testdata/flows/tests.test.ts
packages/functions-runtime/scripts/oas.ts
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/handleFlow.ts
packages/functions-runtime/src/index.ts
runtime/openapi/flowConfig.json
runtime/openapi/openapi.go
runtime/openapi/testdata/flow.json

* Normalise the flow config so we return a most consistent structure over the api 
* Stages are always object format
* Default to flow name if there isn't a title set

fix: normalise flow config

---

tools/diff.go

Improving pagination migrations for tool configs.

fix: nil ref pagination tool migrations

---

tools/proto/tools.proto

* Tools config for a quick search field
* Lays the foundation for richer filter config

feat: quick search config

---

tools/testdata/blog/tools.json
tools/testdata/config_use_api/tools.json
tools/testdata/entry_activity_actions/tools.json
tools/testdata/facets/tools.json
tools/testdata/flows/tools.json
tools/testdata/generate_testdata.go
tools/testdata/input_get_entry_actions/tools.json
tools/testdata/input_get_entry_actions_with_relationships/tools.json
tools/testdata/input_lookup_actions/tools.json
tools/testdata/input_lookup_actions_with_relationships/tools.json
tools/testdata/nested_inputs/tools.json
tools/testdata/nested_outputs/tools.json
tools/testdata/one_to_many_links/tools.json
tools/testdata/with_api_definition_no_config/tools.json
tools/tools_test.go

Update tool generation tests to use the new `Tool` wrapper. This will now assert the generation of both Action and Flow based tools

test: update tools generation test to new Tool wrapper

---

testing/aws.go

Some tests have been randomly failing, I believe this is due to concurrent map reads/writes when handling files. This PR adds a mutex whenever the aws test handler handles files

fix: prevent concurrent reads/writes in aws tests

---

expressions/options/options.go
expressions/parser.go
expressions/typing/provider.go
expressions/typing/types.go

Cleaning up some of the CEL types.

chore: cleaning up cel types

---

packages/functions-runtime/src/flows/ui/page.ts
runtime/openapi/testdata/flow.json
runtime/openapi/uiConfig.json

Always send the full object format over the api

fix: normalise page action config

---

packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/ui/elements/input/dataGrid.test-d.ts
packages/functions-runtime/src/flows/ui/elements/input/dataGrid.test.ts
packages/functions-runtime/src/flows/ui/elements/input/dataGrid.ts
packages/functions-runtime/src/flows/ui/index.ts
runtime/openapi/testdata/flow.json
runtime/openapi/uiConfig.json

* Data grid input element to render a spreadsheet like interface to capture / edit information
* Can provide data to fill the grid
* Column names and types are inferred from the data
* Columns can be defined to set specific types / filter the data to just a sub set of columns
* If the columns cast the data into a differnt type the response type of the element follows the new column type

Data grid element

---

go.mod
go.sum
packages/client-react-query/package.json
packages/client-react-query/pnpm-lock.yaml
packages/client-react/pnpm-lock.yaml
packages/functions-runtime/package.json
packages/functions-runtime/pnpm-lock.yaml
packages/keel/pnpm-lock.yaml
packages/testing-runtime/package.json
packages/testing-runtime/pnpm-lock.yaml
packages/wasm/package.json
packages/wasm/pnpm-lock.yaml

Updates to all Go and node package dependencies within range.

chore: go and node dependency updates

---

migrations/migrations.go
migrations/tasks.sql

SQL migrations for tasks db tables.

chore: tasks queue sql migrations

---

deploy/build.go
deploy/lambdas/functions/main.js.go.tmpl
node/codegen.go
node/codegen_test.go
node/node.go
node/scaffold.go
node/scaffold_test.go
proto/entity.go
proto/schema.go
runtime/flows/authorisation.go
runtime/openapi/flowsapi.go
schema/testdata/errors/tasks_duplicate_names.keel
schema/validation/duplicate_task_names.go

* Scaffolds flow functions for each declared task/topic.
* Update validation rule to avoid name clashes between entities, flows, messages

chore: scaffold flows for tasks

---

node/codegen.go
node/codegen_test.go
packages/functions-runtime/src/flows/index.ts
packages/functions-runtime/src/flows/testingUtils.ts
packages/functions-runtime/src/flows/ui/elements/interactive/print.test-d.ts
packages/functions-runtime/src/flows/ui/elements/interactive/print.test.ts
packages/functions-runtime/src/flows/ui/elements/interactive/print.ts
packages/functions-runtime/src/flows/ui/index.ts
runtime/openapi/testdata/flow.json
runtime/openapi/uiConfig.json

- Pass hardware configuration into Flow context through codegen
- Print element supports printer selection for each job

chore: pass printer options to print element
